/* The question bank.  Each entry carries the function, the point, and the
   exact derivative; tests.js checks every `fp` against a finite-difference
   approximation of `f`, so a typo in a derivative cannot reach a student.

   `window` is the x-interval the graph opens on.  It exists to keep vertical
   asymptotes and undefined regions off the edge of the picture, since the
   y-range is inferred from whatever the function does across it. */

const PROBLEMS = [
  {
    topic: "Power rule",
    tex: "f(x) = x^{3} - 4x + 1",
    f: x => x ** 3 - 4 * x + 1,
    fp: x => 3 * x ** 2 - 4,
    fpTex: "f'(x) = 3x^{2} - 4",
    a: 2, aTex: "2", answerTex: "8",
    window: [-3, 3],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = \\dfrac{1}{x^{2}}",
    f: x => 1 / x ** 2,
    fp: x => -2 / x ** 3,
    fpTex: "f'(x) = -\\dfrac{2}{x^{3}}",
    a: 2, aTex: "2", answerTex: "-\\dfrac{1}{4}",
    window: [0.4, 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = \\sqrt{x}",
    f: x => Math.sqrt(x),
    fp: x => 1 / (2 * Math.sqrt(x)),
    fpTex: "f'(x) = \\dfrac{1}{2\\sqrt{x}}",
    a: 9, aTex: "9", answerTex: "\\dfrac{1}{6}",
    window: [0, 16],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{4} - 2x^{2}",
    f: x => x ** 4 - 2 * x ** 2,
    fp: x => 4 * x ** 3 - 4 * x,
    fpTex: "f'(x) = 4x^{3} - 4x",
    a: -1, aTex: "-1", answerTex: "0",
    window: [-2, 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = x^{2}e^{x}",
    f: x => x ** 2 * Math.exp(x),
    fp: x => (x ** 2 + 2 * x) * Math.exp(x),
    fpTex: "f'(x) = (x^{2} + 2x)e^{x}",
    a: 1, aTex: "1", answerTex: "3e",
    window: [-4, 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = x\\sin x",
    f: x => x * Math.sin(x),
    fp: x => Math.sin(x) + x * Math.cos(x),
    fpTex: "f'(x) = \\sin x + x\\cos x",
    a: Math.PI, aTex: "\\pi", answerTex: "-\\pi",
    window: [-2 * Math.PI, 2 * Math.PI],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{x + 1}",
    f: x => x / (x + 1),
    fp: x => 1 / (x + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{1}{(x + 1)^{2}}",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{4}",
    window: [-0.5, 5],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2} - 1}{x^{2} + 1}",
    f: x => (x ** 2 - 1) / (x ** 2 + 1),
    fp: x => (4 * x) / (x ** 2 + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{4x}{(x^{2} + 1)^{2}}",
    a: 1, aTex: "1", answerTex: "1",
    window: [-4, 4],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\sin x}{x}",
    f: x => Math.sin(x) / x,
    fp: x => (x * Math.cos(x) - Math.sin(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{x\\cos x - \\sin x}{x^{2}}",
    a: Math.PI, aTex: "\\pi", answerTex: "-\\dfrac{1}{\\pi}",
    window: [0.2, 10],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (2x - 1)^{3}",
    f: x => (2 * x - 1) ** 3,
    fp: x => 6 * (2 * x - 1) ** 2,
    fpTex: "f'(x) = 6(2x - 1)^{2}",
    a: 1, aTex: "1", answerTex: "6",
    window: [-1, 3],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{x^{2} + 9}",
    f: x => Math.sqrt(x ** 2 + 9),
    fp: x => x / Math.sqrt(x ** 2 + 9),
    fpTex: "f'(x) = \\dfrac{x}{\\sqrt{x^{2} + 9}}",
    a: 4, aTex: "4", answerTex: "\\dfrac{4}{5}",
    window: [-6, 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(2x)",
    f: x => Math.sin(2 * x),
    fp: x => 2 * Math.cos(2 * x),
    fpTex: "f'(x) = 2\\cos(2x)",
    a: Math.PI / 6, aTex: "\\dfrac{\\pi}{6}", answerTex: "1",
    window: [-Math.PI, Math.PI],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{-x^{2}}",
    f: x => Math.exp(-(x ** 2)),
    fp: x => -2 * x * Math.exp(-(x ** 2)),
    fpTex: "f'(x) = -2xe^{-x^{2}}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{2}{e}",
    window: [-3, 3],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\cos x",
    f: x => Math.cos(x),
    fp: x => -Math.sin(x),
    fpTex: "f'(x) = -\\sin x",
    a: Math.PI / 4, aTex: "\\dfrac{\\pi}{4}", answerTex: "-\\dfrac{\\sqrt{2}}{2}",
    window: [-2 * Math.PI, 2 * Math.PI],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\tan x",
    f: x => Math.tan(x),
    fp: x => 1 / Math.cos(x) ** 2,
    fpTex: "f'(x) = \\sec^{2} x",
    a: Math.PI / 4, aTex: "\\dfrac{\\pi}{4}", answerTex: "2",
    window: [-1.4, 1.4],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln x",
    f: x => Math.log(x),
    fp: x => 1 / x,
    fpTex: "f'(x) = \\dfrac{1}{x}",
    a: 4, aTex: "4", answerTex: "\\dfrac{1}{4}",
    window: [0.1, 10],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\ln(x^{2} + 1)",
    f: x => Math.log(x ** 2 + 1),
    fp: x => (2 * x) / (x ** 2 + 1),
    fpTex: "f'(x) = \\dfrac{2x}{x^{2} + 1}",
    a: 1, aTex: "1", answerTex: "1",
    window: [-4, 4],
  },

  /* ---- Power rule ---- */
  {
    topic: "Power rule",
    tex: "f(x) = 3x^{2} + 4x + 1",
    f: x => 3 * x ** 2 + 4 * x + 1,
    fp: x => 6 * x + 4,
    fpTex: "f'(x) = 6x + 4",
    a: 0, aTex: "0", answerTex: "4",
    window: [-3, 3],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{2} - x - 1",
    f: x => -(x ** 2) - x - 1,
    fp: x => -2 * x - 1,
    fpTex: "f'(x) = -2x - 1",
    a: 1, aTex: "1", answerTex: "-3",
    window: [-2, 4],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{2} + 4x + 2",
    f: x => x ** 2 + 4 * x + 2,
    fp: x => 2 * x + 4,
    fpTex: "f'(x) = 2x + 4",
    a: 3, aTex: "3", answerTex: "10",
    window: [0, 6],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{2} - 2x + 2",
    f: x => 2 * x ** 2 - 2 * x + 2,
    fp: x => 4 * x - 2,
    fpTex: "f'(x) = 4x - 2",
    a: 3, aTex: "3", answerTex: "10",
    window: [0, 6],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{2} - 6x",
    f: x => x ** 2 - 6 * x,
    fp: x => 2 * x - 6,
    fpTex: "f'(x) = 2x - 6",
    a: 3, aTex: "3", answerTex: "0",
    window: [0, 6],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 3x^{2} + x + 1",
    f: x => 3 * x ** 2 + x + 1,
    fp: x => 6 * x + 1,
    fpTex: "f'(x) = 6x + 1",
    a: -1, aTex: "-1", answerTex: "-5",
    window: [-4, 2],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{2} - 2x + 5",
    f: x => x ** 2 - 2 * x + 5,
    fp: x => 2 * x - 2,
    fpTex: "f'(x) = 2x - 2",
    a: 2, aTex: "2", answerTex: "2",
    window: [-1, 5],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{3} - 2x^{2} - x + 1",
    f: x => 2 * x ** 3 - 2 * x ** 2 - x + 1,
    fp: x => 6 * x ** 2 - 4 * x - 1,
    fpTex: "f'(x) = 6x^{2} - 4x - 1",
    a: 0, aTex: "0", answerTex: "-1",
    window: [-3, 3],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{3} - 2x^{2} + 2x + 1",
    f: x => -(x ** 3) - 2 * x ** 2 + 2 * x + 1,
    fp: x => -(3 * x ** 2) - 4 * x + 2,
    fpTex: "f'(x) = -3x^{2} - 4x + 2",
    a: 1, aTex: "1", answerTex: "-5",
    window: [-2, 4],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{3} + 2x^{2} + 2x",
    f: x => -(x ** 3) + 2 * x ** 2 + 2 * x,
    fp: x => -(3 * x ** 2) + 4 * x + 2,
    fpTex: "f'(x) = -3x^{2} + 4x + 2",
    a: 2, aTex: "2", answerTex: "-2",
    window: [-1, 5],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{3} - x^{2} - x + 4",
    f: x => -(x ** 3) - x ** 2 - x + 4,
    fp: x => -(3 * x ** 2) - 2 * x - 1,
    fpTex: "f'(x) = -3x^{2} - 2x - 1",
    a: 0, aTex: "0", answerTex: "-1",
    window: [-3, 3],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{3} - 3x^{2} - 4x",
    f: x => x ** 3 - 3 * x ** 2 - 4 * x,
    fp: x => 3 * x ** 2 - 6 * x - 4,
    fpTex: "f'(x) = 3x^{2} - 6x - 4",
    a: -2, aTex: "-2", answerTex: "20",
    window: [-5, 1],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{3} - x + 1",
    f: x => 2 * x ** 3 - x + 1,
    fp: x => 6 * x ** 2 - 1,
    fpTex: "f'(x) = 6x^{2} - 1",
    a: 2, aTex: "2", answerTex: "23",
    window: [-1, 5],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{3} - 2x^{2} - x - 2",
    f: x => 2 * x ** 3 - 2 * x ** 2 - x - 2,
    fp: x => 6 * x ** 2 - 4 * x - 1,
    fpTex: "f'(x) = 6x^{2} - 4x - 1",
    a: -1, aTex: "-1", answerTex: "9",
    window: [-4, 2],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{4} - 2x^{2}",
    f: x => x ** 4 - 2 * x ** 2,
    fp: x => 4 * x ** 3 - 4 * x,
    fpTex: "f'(x) = 4x^{3} - 4x",
    a: -2, aTex: "-2", answerTex: "-24",
    window: [-5, 1],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{4} - 2x^{2} + 2",
    f: x => 2 * x ** 4 - 2 * x ** 2 + 2,
    fp: x => 8 * x ** 3 - 4 * x,
    fpTex: "f'(x) = 8x^{3} - 4x",
    a: -1, aTex: "-1", answerTex: "-4",
    window: [-4, 2],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{4} - 2x^{2} + 2",
    f: x => -(x ** 4) - 2 * x ** 2 + 2,
    fp: x => -(4 * x ** 3) - 4 * x,
    fpTex: "f'(x) = -4x^{3} - 4x",
    a: -3, aTex: "-3", answerTex: "120",
    window: [-6, 0],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{4} - 3x^{2}",
    f: x => 2 * x ** 4 - 3 * x ** 2,
    fp: x => 8 * x ** 3 - 6 * x,
    fpTex: "f'(x) = 8x^{3} - 6x",
    a: -2, aTex: "-2", answerTex: "-52",
    window: [-5, 1],
  },
  {
    topic: "Power rule",
    tex: "f(x) = 2x^{4} - 3x^{2} + 2",
    f: x => 2 * x ** 4 - 3 * x ** 2 + 2,
    fp: x => 8 * x ** 3 - 6 * x,
    fpTex: "f'(x) = 8x^{3} - 6x",
    a: 0, aTex: "0", answerTex: "0",
    window: [-3, 3],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{4} + x^{2}",
    f: x => x ** 4 + x ** 2,
    fp: x => 4 * x ** 3 + 2 * x,
    fpTex: "f'(x) = 4x^{3} + 2x",
    a: -1, aTex: "-1", answerTex: "-6",
    window: [-4, 2],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{4} - 2x^{2} + 2",
    f: x => x ** 4 - 2 * x ** 2 + 2,
    fp: x => 4 * x ** 3 - 4 * x,
    fpTex: "f'(x) = 4x^{3} - 4x",
    a: -2, aTex: "-2", answerTex: "-24",
    window: [-5, 1],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{4} - 2x^{2} - 1",
    f: x => -(x ** 4) - 2 * x ** 2 - 1,
    fp: x => -(4 * x ** 3) - 4 * x,
    fpTex: "f'(x) = -4x^{3} - 4x",
    a: -2, aTex: "-2", answerTex: "40",
    window: [-5, 1],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{5} + 3x",
    f: x => -(x ** 5) + 3 * x,
    fp: x => -(5 * x ** 4) + 3,
    fpTex: "f'(x) = -5x^{4} + 3",
    a: -2, aTex: "-2", answerTex: "-77",
    window: [-4, 0],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{5} + x^{3}",
    f: x => x ** 5 + x ** 3,
    fp: x => 5 * x ** 4 + 3 * x ** 2,
    fpTex: "f'(x) = 5x^{4} + 3x^{2}",
    a: 2, aTex: "2", answerTex: "92",
    window: [0, 4],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{5} - 2x^{3} - 4x",
    f: x => -(x ** 5) - 2 * x ** 3 - 4 * x,
    fp: x => -(5 * x ** 4) - 6 * x ** 2 - 4,
    fpTex: "f'(x) = -5x^{4} - 6x^{2} - 4",
    a: 2, aTex: "2", answerTex: "-108",
    window: [0, 4],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{5} + x^{3} + 3x",
    f: x => x ** 5 + x ** 3 + 3 * x,
    fp: x => 5 * x ** 4 + 3 * x ** 2 + 3,
    fpTex: "f'(x) = 5x^{4} + 3x^{2} + 3",
    a: 0, aTex: "0", answerTex: "3",
    window: [-3, 3],
  },
  {
    topic: "Power rule",
    tex: "f(x) = -x^{5} - 2x^{3}",
    f: x => -(x ** 5) - 2 * x ** 3,
    fp: x => -(5 * x ** 4) - 6 * x ** 2,
    fpTex: "f'(x) = -5x^{4} - 6x^{2}",
    a: -1, aTex: "-1", answerTex: "-11",
    window: [-4, 2],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{5} + x^{3}",
    f: x => x ** 5 + x ** 3,
    fp: x => 5 * x ** 4 + 3 * x ** 2,
    fpTex: "f'(x) = 5x^{4} + 3x^{2}",
    a: -2, aTex: "-2", answerTex: "92",
    window: [-4, 0],
  },
  {
    topic: "Power rule",
    tex: "f(x) = x^{5} - 2x^{3} + 3x",
    f: x => x ** 5 - 2 * x ** 3 + 3 * x,
    fp: x => 5 * x ** 4 - 6 * x ** 2 + 3,
    fpTex: "f'(x) = 5x^{4} - 6x^{2} + 3",
    a: -1, aTex: "-1", answerTex: "2",
    window: [-4, 2],
  },

  /* ---- Power rule, negative exponent ---- */
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = x - \\dfrac{2}{x}",
    f: x => x ** 1 + -2 * x ** -1,
    fp: x => 1 + 2 * x ** -2,
    fpTex: "f'(x) = 1 + \\dfrac{2}{x^{2}}",
    a: -2, aTex: "-2", answerTex: "\\dfrac{3}{2}",
    window: [-26 / 5, -2 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = 2x - \\dfrac{1}{x}",
    f: x => 2 * x ** 1 + -1 * x ** -1,
    fp: x => 2 + x ** -2,
    fpTex: "f'(x) = 2 + \\dfrac{1}{x^{2}}",
    a: 1 / 2, aTex: "\\dfrac{1}{2}", answerTex: "6",
    window: [1 / 10, 13 / 10],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = 2x + \\dfrac{2}{x}",
    f: x => 2 * x ** 1 + 2 * x ** -1,
    fp: x => 2 + -2 * x ** -2,
    fpTex: "f'(x) = 2 - \\dfrac{2}{x^{2}}",
    a: -2, aTex: "-2", answerTex: "\\dfrac{3}{2}",
    window: [-26 / 5, -2 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = 2x + \\dfrac{3}{x^{2}}",
    f: x => 2 * x ** 1 + 3 * x ** -2,
    fp: x => 2 + -6 * x ** -3,
    fpTex: "f'(x) = 2 - \\dfrac{6}{x^{3}}",
    a: 4, aTex: "4", answerTex: "\\dfrac{61}{32}",
    window: [4 / 5, 52 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = -x - \\dfrac{1}{x^{2}}",
    f: x => -1 * x ** 1 + -1 * x ** -2,
    fp: x => -1 + 2 * x ** -3,
    fpTex: "f'(x) = -1 + \\dfrac{2}{x^{3}}",
    a: -1, aTex: "-1", answerTex: "-3",
    window: [-13 / 5, -1 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = -x + \\dfrac{2}{x^{2}}",
    f: x => -1 * x ** 1 + 2 * x ** -2,
    fp: x => -1 + -4 * x ** -3,
    fpTex: "f'(x) = -1 - \\dfrac{4}{x^{3}}",
    a: 1 / 2, aTex: "\\dfrac{1}{2}", answerTex: "-33",
    window: [1 / 10, 13 / 10],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = -x + \\dfrac{1}{x^{3}}",
    f: x => -1 * x ** 1 + x ** -3,
    fp: x => -1 + -3 * x ** -4,
    fpTex: "f'(x) = -1 - \\dfrac{3}{x^{4}}",
    a: 3, aTex: "3", answerTex: "-\\dfrac{28}{27}",
    window: [3 / 5, 39 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = 2x - \\dfrac{1}{x^{3}}",
    f: x => 2 * x ** 1 + -1 * x ** -3,
    fp: x => 2 + 3 * x ** -4,
    fpTex: "f'(x) = 2 + \\dfrac{3}{x^{4}}",
    a: 1 / 2, aTex: "\\dfrac{1}{2}", answerTex: "50",
    window: [1 / 10, 13 / 10],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = -x + \\dfrac{5}{x^{3}}",
    f: x => -1 * x ** 1 + 5 * x ** -3,
    fp: x => -1 + -15 * x ** -4,
    fpTex: "f'(x) = -1 - \\dfrac{15}{x^{4}}",
    a: 1, aTex: "1", answerTex: "-16",
    window: [1 / 5, 13 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = x + \\dfrac{5}{x^{4}}",
    f: x => x ** 1 + 5 * x ** -4,
    fp: x => 1 + -20 * x ** -5,
    fpTex: "f'(x) = 1 - \\dfrac{20}{x^{5}}",
    a: -2, aTex: "-2", answerTex: "\\dfrac{13}{8}",
    window: [-26 / 5, -2 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = x + \\dfrac{2}{x^{4}}",
    f: x => x ** 1 + 2 * x ** -4,
    fp: x => 1 + -8 * x ** -5,
    fpTex: "f'(x) = 1 - \\dfrac{8}{x^{5}}",
    a: -1, aTex: "-1", answerTex: "9",
    window: [-13 / 5, -1 / 5],
  },
  {
    topic: "Power rule, negative exponent",
    tex: "f(x) = -\\dfrac{1}{x^{4}}",
    f: x => -1 * x ** -4,
    fp: x => 4 * x ** -5,
    fpTex: "f'(x) = \\dfrac{4}{x^{5}}",
    a: 4, aTex: "4", answerTex: "\\dfrac{1}{256}",
    window: [4 / 5, 52 / 5],
  },

  /* ---- Power rule, radical ---- */
  {
    topic: "Power rule, radical",
    tex: "f(x) = \\dfrac{1}{\\sqrt{x}} + x",
    f: x => x ** (-1 / 2) + x ** 1,
    fp: x => (-1 / 2) * x ** (-3 / 2) + 1,
    fpTex: "f'(x) = -\\dfrac{1}{2x\\sqrt{x}} + 1",
    a: 9, aTex: "9", answerTex: "\\dfrac{53}{54}",
    window: [27 / 20, 108 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = -\\dfrac{3}{\\sqrt{x}} + x",
    f: x => -3 * x ** (-1 / 2) + x ** 1,
    fp: x => (3 / 2) * x ** (-3 / 2) + 1,
    fpTex: "f'(x) = \\dfrac{3}{2x\\sqrt{x}} + 1",
    a: 16, aTex: "16", answerTex: "\\dfrac{131}{128}",
    window: [12 / 5, 192 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = -\\dfrac{3}{\\sqrt{x}} + 3x",
    f: x => -3 * x ** (-1 / 2) + 3 * x ** 1,
    fp: x => (3 / 2) * x ** (-3 / 2) + 3,
    fpTex: "f'(x) = \\dfrac{3}{2x\\sqrt{x}} + 3",
    a: 1, aTex: "1", answerTex: "\\dfrac{9}{2}",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = -\\sqrt{x}",
    f: x => -1 * x ** (1 / 2),
    fp: x => (-1 / 2) * x ** (-1 / 2),
    fpTex: "f'(x) = -\\dfrac{1}{2\\sqrt{x}}",
    a: 16, aTex: "16", answerTex: "-\\dfrac{1}{8}",
    window: [12 / 5, 192 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = -\\sqrt{x} + x",
    f: x => -1 * x ** (1 / 2) + x ** 1,
    fp: x => (-1 / 2) * x ** (-1 / 2) + 1,
    fpTex: "f'(x) = -\\dfrac{1}{2\\sqrt{x}} + 1",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{2}",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = 2\\sqrt{x}",
    f: x => 2 * x ** (1 / 2),
    fp: x => x ** (-1 / 2),
    fpTex: "f'(x) = \\dfrac{1}{\\sqrt{x}}",
    a: 1, aTex: "1", answerTex: "1",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = 2\\sqrt[3]{x} - 2x",
    f: x => 2 * Math.cbrt(x) ** 1 + -2 * x ** 1,
    fp: x => (2 / 3) * Math.cbrt(x) ** -2 + -2,
    fpTex: "f'(x) = \\dfrac{2}{3x^{2/3}} - 2",
    a: 8, aTex: "8", answerTex: "-\\dfrac{11}{6}",
    window: [6 / 5, 96 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = \\sqrt[3]{x} - 2x",
    f: x => Math.cbrt(x) ** 1 + -2 * x ** 1,
    fp: x => (1 / 3) * Math.cbrt(x) ** -2 + -2,
    fpTex: "f'(x) = \\dfrac{1}{3x^{2/3}} - 2",
    a: 1, aTex: "1", answerTex: "-\\dfrac{5}{3}",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = 2\\sqrt[3]{x} - 2x",
    f: x => 2 * Math.cbrt(x) ** 1 + -2 * x ** 1,
    fp: x => (2 / 3) * Math.cbrt(x) ** -2 + -2,
    fpTex: "f'(x) = \\dfrac{2}{3x^{2/3}} - 2",
    a: 27, aTex: "27", answerTex: "-\\dfrac{52}{27}",
    window: [81 / 20, 324 / 5],
  },
  {
    topic: "Power rule, radical",
    tex: "f(x) = 2\\sqrt[3]{x}",
    f: x => 2 * Math.cbrt(x) ** 1,
    fp: x => (2 / 3) * Math.cbrt(x) ** -2,
    fpTex: "f'(x) = \\dfrac{2}{3x^{2/3}}",
    a: 64, aTex: "64", answerTex: "\\dfrac{1}{24}",
    window: [48 / 5, 768 / 5],
  },

  /* ---- Power rule, rational exponent ---- */
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = \\dfrac{1}{x^{2/3}} + x",
    f: x => Math.cbrt(x) ** -2 + x ** 1,
    fp: x => (-2 / 3) * Math.cbrt(x) ** -5 + 1,
    fpTex: "f'(x) = -\\dfrac{2}{3x^{5/3}} + 1",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{3}",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{2/3} + x",
    f: x => Math.cbrt(x) ** 2 + x ** 1,
    fp: x => (2 / 3) * Math.cbrt(x) ** -1 + 1,
    fpTex: "f'(x) = \\dfrac{2}{3\\sqrt[3]{x}} + 1",
    a: 64, aTex: "64", answerTex: "\\dfrac{7}{6}",
    window: [48 / 5, 768 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = 2x\\sqrt{x} + 3x",
    f: x => 2 * x ** (3 / 2) + 3 * x ** 1,
    fp: x => 3 * x ** (1 / 2) + 3,
    fpTex: "f'(x) = 3\\sqrt{x} + 3",
    a: 1, aTex: "1", answerTex: "6",
    window: [3 / 20, 12 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{4/3} - 2x",
    f: x => Math.cbrt(x) ** 4 + -2 * x ** 1,
    fp: x => (4 / 3) * Math.cbrt(x) ** 1 + -2,
    fpTex: "f'(x) = \\dfrac{4\\sqrt[3]{x}}{3} - 2",
    a: 1, aTex: "1", answerTex: "-\\dfrac{2}{3}",
    window: [0, 11 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{4/3} + 3x",
    f: x => Math.cbrt(x) ** 4 + 3 * x ** 1,
    fp: x => (4 / 3) * Math.cbrt(x) ** 1 + 3,
    fpTex: "f'(x) = \\dfrac{4\\sqrt[3]{x}}{3} + 3",
    a: 27, aTex: "27", answerTex: "7",
    window: [0, 297 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{5/2}",
    f: x => x ** (5 / 2),
    fp: x => (5 / 2) * x ** (3 / 2),
    fpTex: "f'(x) = \\dfrac{5x\\sqrt{x}}{2}",
    a: 4, aTex: "4", answerTex: "20",
    window: [3 / 5, 48 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{5/3} + 3x",
    f: x => Math.cbrt(x) ** 5 + 3 * x ** 1,
    fp: x => (5 / 3) * Math.cbrt(x) ** 2 + 3,
    fpTex: "f'(x) = \\dfrac{5x^{2/3}}{3} + 3",
    a: 1, aTex: "1", answerTex: "\\dfrac{14}{3}",
    window: [0, 11 / 5],
  },
  {
    topic: "Power rule, rational exponent",
    tex: "f(x) = x^{5/3} + x",
    f: x => Math.cbrt(x) ** 5 + x ** 1,
    fp: x => (5 / 3) * Math.cbrt(x) ** 2 + 1,
    fpTex: "f'(x) = \\dfrac{5x^{2/3}}{3} + 1",
    a: 1, aTex: "1", answerTex: "\\dfrac{8}{3}",
    window: [0, 11 / 5],
  },

  /* ---- Horizontal tangent ---- */
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{3} - 3x",
    f: x => x ** 3 - 3 * x,
    fp: x => 3 * x ** 2 - 3,
    fpTex: "f'(x) = 3x^{2} - 3",
    a: -1, aTex: "-1", answerTex: "0",
    window: [-4, 2],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = e^{-x^{2}}",
    f: x => Math.exp(-(x ** 2)),
    fp: x => -2 * x * Math.exp(-(x ** 2)),
    fpTex: "f'(x) = -2xe^{-x^{2}}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-3, 3],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = \\ln x - x",
    f: x => Math.log(x) - x,
    fp: x => 1 / x - 1,
    fpTex: "f'(x) = \\dfrac{1}{x} - 1",
    a: 1, aTex: "1", answerTex: "0",
    window: [1 / 10, 4],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{4} - 8x^{2}",
    f: x => x ** 4 - 8 * x ** 2,
    fp: x => 4 * x ** 3 - 16 * x,
    fpTex: "f'(x) = 4x^{3} - 16x",
    a: -2, aTex: "-2", answerTex: "0",
    window: [-4, 4],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{4} - 18x^{2}",
    f: x => x ** 4 - 18 * x ** 2,
    fp: x => 4 * x ** 3 - 36 * x,
    fpTex: "f'(x) = 4x^{3} - 36x",
    a: -3, aTex: "-3", answerTex: "0",
    window: [-6, 6],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = \\dfrac{x}{x^{2} + 4}",
    f: x => x / (x ** 2 + 4),
    fp: x => (4 - x ** 2) / (x ** 2 + 4) ** 2,
    fpTex: "f'(x) = \\dfrac{4 - x^{2}}{(x^{2} + 4)^{2}}",
    a: 2, aTex: "2", answerTex: "0",
    window: [-6, 6],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = \\sin x",
    f: x => Math.sin(x),
    fp: x => Math.cos(x),
    fpTex: "f'(x) = \\cos x",
    a: 3 * Math.PI / 2, aTex: "\\dfrac{3\\pi}{2}", answerTex: "0",
    window: [Math.PI / 2, 5 * Math.PI / 2],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = \\sin x",
    f: x => Math.sin(x),
    fp: x => Math.cos(x),
    fpTex: "f'(x) = \\cos x",
    a: -Math.PI / 2, aTex: "-\\dfrac{\\pi}{2}", answerTex: "0",
    window: [-3 * Math.PI / 2, Math.PI / 2],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{2} + 6x",
    f: x => x ** 2 + 6 * x,
    fp: x => 2 * x + 6,
    fpTex: "f'(x) = 2x + 6",
    a: -3, aTex: "-3", answerTex: "0",
    window: [-6, 0],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x\\ln x",
    f: x => x * Math.log(x),
    fp: x => Math.log(x) + 1,
    fpTex: "f'(x) = \\ln x + 1",
    a: 1 / Math.E, aTex: "\\dfrac{1}{e}", answerTex: "0",
    window: [1 / 50, 7 / 5],
  },
  {
    topic: "Horizontal tangent",
    tex: "f(x) = x^{3}e^{x}",
    f: x => x ** 3 * Math.exp(x),
    fp: x => (x ** 3 + 3 * x ** 2) * Math.exp(x),
    fpTex: "f'(x) = (x^{3} + 3x^{2})e^{x}",
    a: -3, aTex: "-3", answerTex: "0",
    window: [-6, 3 / 2],
  },

  /* ---- Product rule ---- */
  {
    topic: "Product rule",
    tex: "f(x) = e^{x}\\cos x",
    f: x => Math.exp(x) * Math.cos(x),
    fp: x => Math.exp(x) * (Math.cos(x) - Math.sin(x)),
    fpTex: "f'(x) = e^{x}(\\cos x - \\sin x)",
    a: 0, aTex: "0", answerTex: "1",
    window: [-3, 3 / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = e^{x}\\cos x",
    f: x => Math.exp(x) * Math.cos(x),
    fp: x => Math.exp(x) * (Math.cos(x) - Math.sin(x)),
    fpTex: "f'(x) = e^{x}(\\cos x - \\sin x)",
    a: Math.PI, aTex: "\\pi", answerTex: "-e^\\pi",
    window: [0.1416, 4.6416],
  },
  {
    topic: "Product rule",
    tex: "f(x) = e^{x}\\sin x",
    f: x => Math.exp(x) * Math.sin(x),
    fp: x => Math.exp(x) * (Math.sin(x) + Math.cos(x)),
    fpTex: "f'(x) = e^{x}(\\sin x + \\cos x)",
    a: Math.PI, aTex: "\\pi", answerTex: "-e^\\pi",
    window: [0.1416, 4.6416],
  },
  {
    topic: "Product rule",
    tex: "f(x) = e^{x}\\sin x",
    f: x => Math.exp(x) * Math.sin(x),
    fp: x => Math.exp(x) * (Math.sin(x) + Math.cos(x)),
    fpTex: "f'(x) = e^{x}(\\sin x + \\cos x)",
    a: 0, aTex: "0", answerTex: "1",
    window: [-3, 3 / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = (-x^{2} + 1)(2x - 1)",
    f: x => (-(x ** 2) + 1) * (2 * x - 1),
    fp: x => (-2 * x) * (2 * x - 1) + (-(x ** 2) + 1) * (2),
    fpTex: "f'(x) = -2x(2x - 1) + (-x^{2} + 1)2",
    a: -1, aTex: "-1", answerTex: "-6",
    window: [-4, 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = (2x^{2} - 1)(x + 2)",
    f: x => (2 * x ** 2 - 1) * (x + 2),
    fp: x => (4 * x) * (x + 2) + (2 * x ** 2 - 1) * (1),
    fpTex: "f'(x) = 4x(x + 2) + (2x^{2} - 1)",
    a: -2, aTex: "-2", answerTex: "7",
    window: [-5, 1],
  },
  {
    topic: "Product rule",
    tex: "f(x) = (-x^{2} + 3)(x - 3)",
    f: x => (-(x ** 2) + 3) * (x - 3),
    fp: x => (-2 * x) * (x - 3) + (-(x ** 2) + 3) * (1),
    fpTex: "f'(x) = -2x(x - 3) + (-x^{2} + 3)",
    a: 0, aTex: "0", answerTex: "3",
    window: [-3, 3],
  },
  {
    topic: "Product rule",
    tex: "f(x) = \\sin x\\cos x",
    f: x => Math.sin(x) * Math.cos(x),
    fp: x => Math.cos(x) ** 2 - Math.sin(x) ** 2,
    fpTex: "f'(x) = \\cos^{2} x - \\sin^{2} x",
    a: Math.PI / 2, aTex: "\\dfrac{\\pi}{2}", answerTex: "-1",
    window: [-Math.PI / 2, 3 * Math.PI / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = \\sin x\\cos x",
    f: x => Math.sin(x) * Math.cos(x),
    fp: x => Math.cos(x) ** 2 - Math.sin(x) ** 2,
    fpTex: "f'(x) = \\cos^{2} x - \\sin^{2} x",
    a: -Math.PI / 4, aTex: "-\\dfrac{\\pi}{4}", answerTex: "0",
    window: [-5 * Math.PI / 4, 3 * Math.PI / 4],
  },
  {
    topic: "Product rule",
    tex: "f(x) = \\sqrt{x}e^{x}",
    f: x => Math.sqrt(x) * Math.exp(x),
    fp: x => Math.exp(x) * (Math.sqrt(x) + 1 / (2 * Math.sqrt(x))),
    fpTex: "f'(x) = e^{x}\\left(\\sqrt{x} + \\dfrac{1}{2\\sqrt{x}}\\right)",
    a: 4, aTex: "4", answerTex: "\\dfrac{9e^4}{4}",
    window: [1 / 20, 26 / 5],
  },
  {
    topic: "Product rule",
    tex: "f(x) = \\sqrt{x}e^{x}",
    f: x => Math.sqrt(x) * Math.exp(x),
    fp: x => Math.exp(x) * (Math.sqrt(x) + 1 / (2 * Math.sqrt(x))),
    fpTex: "f'(x) = e^{x}\\left(\\sqrt{x} + \\dfrac{1}{2\\sqrt{x}}\\right)",
    a: 1, aTex: "1", answerTex: "\\dfrac{3e}{2}",
    window: [1 / 20, 11 / 5],
  },
  {
    topic: "Product rule",
    tex: "f(x) = -x^{3}\\cos x",
    f: x => -1 * x ** 3 * Math.cos(x),
    fp: x => -1 * (3 * x ** 2 * Math.cos(x) - x ** 3 * Math.sin(x)),
    fpTex: "f'(x) = -(3x^{2}\\cos x - x^{3}\\sin x)",
    a: 2 * Math.PI, aTex: "2\\pi", answerTex: "-12\\pi^2",
    window: [Math.PI, 3 * Math.PI],
  },
  {
    topic: "Product rule",
    tex: "f(x) = -x^{2}\\cos x",
    f: x => -1 * x ** 2 * Math.cos(x),
    fp: x => -1 * (2 * x ** 1 * Math.cos(x) - x ** 2 * Math.sin(x)),
    fpTex: "f'(x) = -(2x\\cos x - x^{2}\\sin x)",
    a: 3 * Math.PI / 2, aTex: "\\dfrac{3\\pi}{2}", answerTex: "-\\dfrac{9\\pi^2}{4}",
    window: [Math.PI / 2, 5 * Math.PI / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = x^{2}\\cos x",
    f: x => 1 * x ** 2 * Math.cos(x),
    fp: x => 1 * (2 * x ** 1 * Math.cos(x) - x ** 2 * Math.sin(x)),
    fpTex: "f'(x) = 2x\\cos x - x^{2}\\sin x",
    a: 3 * Math.PI / 2, aTex: "\\dfrac{3\\pi}{2}", answerTex: "\\dfrac{9\\pi^2}{4}",
    window: [Math.PI / 2, 5 * Math.PI / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = 2x^{2}e^{x}",
    f: x => 2 * x ** 2 * Math.exp(x),
    fp: x => 2 * (x ** 2 + 2 * x ** 1) * Math.exp(x),
    fpTex: "f'(x) = 2(x^{2} + 2x)e^{x}",
    a: -2, aTex: "-2", answerTex: "0",
    window: [-5, -1 / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = 3x^{3}e^{x}",
    f: x => 3 * x ** 3 * Math.exp(x),
    fp: x => 3 * (x ** 3 + 3 * x ** 2) * Math.exp(x),
    fpTex: "f'(x) = 3(x^{3} + 3x^{2})e^{x}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-3, 3 / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = 2x\\ln x",
    f: x => 2 * x ** 1 * Math.log(x),
    fp: x => 2 * x ** 0 * (1 * Math.log(x) + 1),
    fpTex: "f'(x) = 2(\\ln x + 1)",
    a: 1, aTex: "1", answerTex: "2",
    window: [1 / 20, 11 / 5],
  },
  {
    topic: "Product rule",
    tex: "f(x) = x^{3}\\ln x",
    f: x => 1 * x ** 3 * Math.log(x),
    fp: x => 1 * x ** 2 * (3 * Math.log(x) + 1),
    fpTex: "f'(x) = x^{2}(3\\ln x + 1)",
    a: Math.E ** 2, aTex: "e^{2}", answerTex: "7e^4",
    window: [1 / 50, 11.8225],
  },
  {
    topic: "Product rule",
    tex: "f(x) = 2x^{3}\\ln x",
    f: x => 2 * x ** 3 * Math.log(x),
    fp: x => 2 * x ** 2 * (3 * Math.log(x) + 1),
    fpTex: "f'(x) = 2x^{2}(3\\ln x + 1)",
    a: 1, aTex: "1", answerTex: "2",
    window: [1 / 20, 11 / 5],
  },
  {
    topic: "Product rule",
    tex: "f(x) = -x^{2}\\sin x",
    f: x => -1 * x ** 2 * Math.sin(x),
    fp: x => -1 * (2 * x ** 1 * Math.sin(x) + x ** 2 * Math.cos(x)),
    fpTex: "f'(x) = -(2x\\sin x + x^{2}\\cos x)",
    a: 0, aTex: "0", answerTex: "0",
    window: [-Math.PI, Math.PI],
  },
  {
    topic: "Product rule",
    tex: "f(x) = 2x^{2}\\sin x",
    f: x => 2 * x ** 2 * Math.sin(x),
    fp: x => 2 * (2 * x ** 1 * Math.sin(x) + x ** 2 * Math.cos(x)),
    fpTex: "f'(x) = 2(2x\\sin x + x^{2}\\cos x)",
    a: Math.PI, aTex: "\\pi", answerTex: "-2\\pi^2",
    window: [0, 2 * Math.PI],
  },
  {
    topic: "Product rule",
    tex: "f(x) = x^{2}\\sin x",
    f: x => 1 * x ** 2 * Math.sin(x),
    fp: x => 1 * (2 * x ** 1 * Math.sin(x) + x ** 2 * Math.cos(x)),
    fpTex: "f'(x) = 2x\\sin x + x^{2}\\cos x",
    a: 3 * Math.PI / 2, aTex: "\\dfrac{3\\pi}{2}", answerTex: "-3\\pi",
    window: [Math.PI / 2, 5 * Math.PI / 2],
  },
  {
    topic: "Product rule",
    tex: "f(x) = (x + 1)\\sqrt{x}",
    f: x => (x + 1) * Math.sqrt(x),
    fp: x => Math.sqrt(x) + (x + 1) / (2 * Math.sqrt(x)),
    fpTex: "f'(x) = \\sqrt{x} + \\dfrac{x + 1}{2\\sqrt{x}}",
    a: 4, aTex: "4", answerTex: "\\dfrac{13}{4}",
    window: [3 / 5, 48 / 5],
  },
  {
    topic: "Product rule",
    tex: "f(x) = (x - 4)\\sqrt{x}",
    f: x => (x + -4) * Math.sqrt(x),
    fp: x => Math.sqrt(x) + (x + -4) / (2 * Math.sqrt(x)),
    fpTex: "f'(x) = \\sqrt{x} + \\dfrac{x - 4}{2\\sqrt{x}}",
    a: 16, aTex: "16", answerTex: "\\dfrac{11}{2}",
    window: [12 / 5, 192 / 5],
  },

  /* ---- Quotient rule ---- */
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\cos x}{x}",
    f: x => Math.cos(x) / x,
    fp: x => (-x * Math.sin(x) - Math.cos(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{-x\\sin x - \\cos x}{x^{2}}",
    a: Math.PI, aTex: "\\pi", answerTex: "\\dfrac{1}{\\pi^2}",
    window: [9 * Math.PI / 50, 13 * Math.PI / 5],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\cos x}{x}",
    f: x => Math.cos(x) / x,
    fp: x => (-x * Math.sin(x) - Math.cos(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{-x\\sin x - \\cos x}{x^{2}}",
    a: -Math.PI, aTex: "-\\pi", answerTex: "\\dfrac{1}{\\pi^2}",
    window: [-13 * Math.PI / 5, -9 * Math.PI / 50],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{e^{x}}{x}",
    f: x => Math.exp(x) / x,
    fp: x => Math.exp(x) * (x - 1) / x ** 2,
    fpTex: "f'(x) = \\dfrac{e^{x}(x - 1)}{x^{2}}",
    a: 3, aTex: "3", answerTex: "\\dfrac{2e^3}{9}",
    window: [27 / 50, 42 / 5],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{e^{x}}{x}",
    f: x => Math.exp(x) / x,
    fp: x => Math.exp(x) * (x - 1) / x ** 2,
    fpTex: "f'(x) = \\dfrac{e^{x}(x - 1)}{x^{2}}",
    a: 1, aTex: "1", answerTex: "0",
    window: [9 / 50, 14 / 5],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{2x - 1}{2x - 2}",
    f: x => (2 * x - 1) / (2 * x - 2),
    fp: x => -2 / (2 * x - 2) ** 2,
    fpTex: "f'(x) = -\\dfrac{2}{(2x - 2)^{2}}",
    a: 3, aTex: "3", answerTex: "-\\dfrac{1}{8}",
    window: [34 / 25, 8],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{3x + 1}{x + 1}",
    f: x => (3 * x + 1) / (1 * x + 1),
    fp: x => 2 / (1 * x + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{2}{(x + 1)^{2}}",
    a: 3, aTex: "3", answerTex: "\\dfrac{1}{8}",
    window: [-7 / 25, 13],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x - 1}{3 - x}",
    f: x => (1 * x - 1) / (-1 * x + 3),
    fp: x => 2 / (-1 * x + 3) ** 2,
    fpTex: "f'(x) = \\dfrac{2}{(3 - x)^{2}}",
    a: -2, aTex: "-2", answerTex: "\\dfrac{2}{25}",
    window: [-29 / 2, 21 / 10],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\ln x}{x}",
    f: x => Math.log(x) / x,
    fp: x => (1 - Math.log(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{1 - \\ln x}{x^{2}}",
    a: Math.E ** 2, aTex: "e^{2}", answerTex: "-\\dfrac{1}{e^4}",
    window: [2 / 25, 16.2559],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\ln x}{x}",
    f: x => Math.log(x) / x,
    fp: x => (1 - Math.log(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{1 - \\ln x}{x^{2}}",
    a: 1, aTex: "1", answerTex: "1",
    window: [2 / 25, 11 / 5],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2} + 3}{x^{2} + 9}",
    f: x => (x ** 2 + 3) / (x ** 2 + 9),
    fp: x => (12 * x) / (x ** 2 + 9) ** 2,
    fpTex: "f'(x) = \\dfrac{12x}{(x^{2} + 9)^{2}}",
    a: 2, aTex: "2", answerTex: "\\dfrac{24}{169}",
    window: [-2, 6],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2} + 1}{x^{2} + 2}",
    f: x => (x ** 2 + 1) / (x ** 2 + 2),
    fp: x => (2 * x) / (x ** 2 + 2) ** 2,
    fpTex: "f'(x) = \\dfrac{2x}{(x^{2} + 2)^{2}}",
    a: 3, aTex: "3", answerTex: "\\dfrac{6}{121}",
    window: [-1, 7],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2} + 3}{x^{2} + 9}",
    f: x => (x ** 2 + 3) / (x ** 2 + 9),
    fp: x => (12 * x) / (x ** 2 + 9) ** 2,
    fpTex: "f'(x) = \\dfrac{12x}{(x^{2} + 9)^{2}}",
    a: -1, aTex: "-1", answerTex: "-\\dfrac{3}{25}",
    window: [-5, 3],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2} - 4}{x^{2} + 2}",
    f: x => (x ** 2 - 4) / (x ** 2 + 2),
    fp: x => (12 * x) / (x ** 2 + 2) ** 2,
    fpTex: "f'(x) = \\dfrac{12x}{(x^{2} + 2)^{2}}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-4, 4],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{\\sin x}{x}",
    f: x => Math.sin(x) / x,
    fp: x => (x * Math.cos(x) - Math.sin(x)) / x ** 2,
    fpTex: "f'(x) = \\dfrac{x\\cos x - \\sin x}{x^{2}}",
    a: 3 * Math.PI / 2, aTex: "\\dfrac{3\\pi}{2}", answerTex: "\\dfrac{4}{9\\pi^2}",
    window: [0.8482, 39 * Math.PI / 10],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{3}}{x - 2}",
    f: x => x ** 3 / (1 * x - 2),
    fp: x => (3 * x ** 2 * (1 * x - 2) - x ** 3) / (1 * x - 2) ** 2,
    fpTex: "f'(x) = \\dfrac{3x^{2}(x - 2) - x^{3}}{(x - 2)^{2}}",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{5}{2}",
    window: [-12, 32 / 25],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{3}}{x + 1}",
    f: x => x ** 3 / (1 * x + 1),
    fp: x => (3 * x ** 2 * (1 * x + 1) - x ** 3) / (1 * x + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{3x^{2}(x + 1) - x^{3}}{(x + 1)^{2}}",
    a: 1, aTex: "1", answerTex: "\\dfrac{5}{4}",
    window: [-16 / 25, 6],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x^{2}}{x + 2}",
    f: x => x ** 2 / (1 * x + 2),
    fp: x => (2 * x ** 1 * (1 * x + 2) - x ** 2) / (1 * x + 2) ** 2,
    fpTex: "f'(x) = \\dfrac{2x(x + 2) - x^{2}}{(x + 2)^{2}}",
    a: 2, aTex: "2", answerTex: "\\dfrac{3}{4}",
    window: [-32 / 25, 12],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{e^{x}}",
    f: x => x / Math.exp(x),
    fp: x => (1 - x) / Math.exp(x),
    fpTex: "f'(x) = \\dfrac{1 - x}{e^{x}}",
    a: 0, aTex: "0", answerTex: "1",
    window: [-5 / 2, 5 / 2],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{e^{x}}",
    f: x => x / Math.exp(x),
    fp: x => (1 - x) / Math.exp(x),
    fpTex: "f'(x) = \\dfrac{1 - x}{e^{x}}",
    a: 3, aTex: "3", answerTex: "-\\dfrac{2}{e^3}",
    window: [1 / 2, 11 / 2],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{x^{2} + 1}",
    f: x => x / (x ** 2 + 1),
    fp: x => (1 - x ** 2) / (x ** 2 + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{1 - x^{2}}{(x^{2} + 1)^{2}}",
    a: 2, aTex: "2", answerTex: "-\\dfrac{3}{25}",
    window: [-4, 4],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{x^{2} + 1}",
    f: x => x / (x ** 2 + 1),
    fp: x => (1 - x ** 2) / (x ** 2 + 1) ** 2,
    fpTex: "f'(x) = \\dfrac{1 - x^{2}}{(x^{2} + 1)^{2}}",
    a: 3, aTex: "3", answerTex: "-\\dfrac{2}{25}",
    window: [-4, 4],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{x^{2} + 9}",
    f: x => x / (x ** 2 + 9),
    fp: x => (9 - x ** 2) / (x ** 2 + 9) ** 2,
    fpTex: "f'(x) = \\dfrac{9 - x^{2}}{(x^{2} + 9)^{2}}",
    a: -1, aTex: "-1", answerTex: "\\dfrac{2}{25}",
    window: [-4, 4],
  },
  {
    topic: "Quotient rule",
    tex: "f(x) = \\dfrac{x}{x^{2} + 2}",
    f: x => x / (x ** 2 + 2),
    fp: x => (2 - x ** 2) / (x ** 2 + 2) ** 2,
    fpTex: "f'(x) = \\dfrac{2 - x^{2}}{(x^{2} + 2)^{2}}",
    a: 3, aTex: "3", answerTex: "-\\dfrac{7}{121}",
    window: [-4, 4],
  },

  /* ---- Chain rule ---- */
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(2 - x)^{3}}",
    f: x => 1 / (-1 * x + 2) ** 3,
    fp: x => 3 / (-1 * x + 2) ** 4,
    fpTex: "f'(x) = \\dfrac{3}{(2 - x)^{4}}",
    a: 1, aTex: "1", answerTex: "3",
    window: [-6 / 5, 91 / 50],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x + 2)}",
    f: x => 1 / (1 * x + 2) ** 1,
    fp: x => -1 / (1 * x + 2) ** 2,
    fpTex: "f'(x) = -\\dfrac{1}{(x + 2)^{2}}",
    a: -1, aTex: "-1", answerTex: "-1",
    window: [-91 / 50, 6 / 5],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(2x - 3)^{2}}",
    f: x => 1 / (2 * x - 3) ** 2,
    fp: x => -4 / (2 * x - 3) ** 3,
    fpTex: "f'(x) = -\\dfrac{4}{(2x - 3)^{3}}",
    a: 1, aTex: "1", answerTex: "4",
    window: [-1 / 10, 1.41],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x - 3)^{2}}",
    f: x => 1 / (1 * x - 3) ** 2,
    fp: x => -2 / (1 * x - 3) ** 3,
    fpTex: "f'(x) = -\\dfrac{2}{(x - 3)^{3}}",
    a: -1, aTex: "-1", answerTex: "\\dfrac{1}{32}",
    window: [-49 / 5, 57 / 25],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(1 - x)^{3}}",
    f: x => 1 / (-1 * x + 1) ** 3,
    fp: x => 3 / (-1 * x + 1) ** 4,
    fpTex: "f'(x) = \\dfrac{3}{(1 - x)^{4}}",
    a: -1, aTex: "-1", answerTex: "\\dfrac{3}{16}",
    window: [-27 / 5, 16 / 25],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (2x - 3)^{2}",
    f: x => (2 * x - 3) ** 2,
    fp: x => 4 * (2 * x - 3) ** 1,
    fpTex: "f'(x) = 4(2x - 3)",
    a: 1, aTex: "1", answerTex: "-4",
    window: [-1, 3],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (x - 1)^{5}",
    f: x => (1 * x - 1) ** 5,
    fp: x => 5 * (1 * x - 1) ** 4,
    fpTex: "f'(x) = 5(x - 1)^{4}",
    a: 2, aTex: "2", answerTex: "5",
    window: [0, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (-2x - 1)^{2}",
    f: x => (-2 * x - 1) ** 2,
    fp: x => -4 * (-2 * x - 1) ** 1,
    fpTex: "f'(x) = -4(-2x - 1)",
    a: 2, aTex: "2", answerTex: "20",
    window: [0, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (-x - 3)^{3}",
    f: x => (-1 * x - 3) ** 3,
    fp: x => -3 * (-1 * x - 3) ** 2,
    fpTex: "f'(x) = -3(-x - 3)^{2}",
    a: 2, aTex: "2", answerTex: "-75",
    window: [0, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (1 - x)^{2}",
    f: x => (-1 * x + 1) ** 2,
    fp: x => -2 * (-1 * x + 1) ** 1,
    fpTex: "f'(x) = -2(1 - x)",
    a: 0, aTex: "0", answerTex: "-2",
    window: [-2, 2],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x^{2} + 2)}",
    f: x => 1 / (x ** 2 + 2) ** 1,
    fp: x => -2 * x / (x ** 2 + 2) ** 2,
    fpTex: "f'(x) = -\\dfrac{2x}{(x^{2} + 2)^{2}}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{2}{9}",
    window: [-4, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x^{2} + 1)^{2}}",
    f: x => 1 / (x ** 2 + 1) ** 2,
    fp: x => -4 * x / (x ** 2 + 1) ** 3,
    fpTex: "f'(x) = -\\dfrac{4x}{(x^{2} + 1)^{3}}",
    a: 2, aTex: "2", answerTex: "-\\dfrac{8}{125}",
    window: [-4, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x^{2} + 2)}",
    f: x => 1 / (x ** 2 + 2) ** 1,
    fp: x => -2 * x / (x ** 2 + 2) ** 2,
    fpTex: "f'(x) = -\\dfrac{2x}{(x^{2} + 2)^{2}}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-4, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x^{2} + 1)^{2}}",
    f: x => 1 / (x ** 2 + 1) ** 2,
    fp: x => -4 * x / (x ** 2 + 1) ** 3,
    fpTex: "f'(x) = -\\dfrac{4x}{(x^{2} + 1)^{3}}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{1}{2}",
    window: [-4, 4],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = \\dfrac{1}{(x^{2} + 1)}",
    f: x => 1 / (x ** 2 + 1) ** 1,
    fp: x => -2 * x / (x ** 2 + 1) ** 2,
    fpTex: "f'(x) = -\\dfrac{2x}{(x^{2} + 1)^{2}}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-3, 3],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (x^{2} + 1)^{3}",
    f: x => (x ** 2 + 1) ** 3,
    fp: x => 6 * x * (x ** 2 + 1) ** 2,
    fpTex: "f'(x) = 6x(x^{2} + 1)^{2}",
    a: 0, aTex: "0", answerTex: "0",
    window: [-2, 2],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (x^{2} - 4)^{2}",
    f: x => (x ** 2 - 4) ** 2,
    fp: x => 4 * x * (x ** 2 - 4) ** 1,
    fpTex: "f'(x) = 4x(x^{2} - 4)",
    a: -1, aTex: "-1", answerTex: "12",
    window: [-3, 1],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (x^{2} - 4)^{3}",
    f: x => (x ** 2 - 4) ** 3,
    fp: x => 6 * x * (x ** 2 - 4) ** 2,
    fpTex: "f'(x) = 6x(x^{2} - 4)^{2}",
    a: -1, aTex: "-1", answerTex: "-54",
    window: [-3, 1],
  },
  {
    topic: "Chain rule",
    tex: "f(x) = (x^{2} - 1)^{4}",
    f: x => (x ** 2 - 1) ** 4,
    fp: x => 8 * x * (x ** 2 - 1) ** 3,
    fpTex: "f'(x) = 8x(x^{2} - 1)^{3}",
    a: 1, aTex: "1", answerTex: "0",
    window: [-1 / 2, 5 / 2],
  },

  /* ---- Chain rule, radical ---- */
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt[3]{2x + 8}",
    f: x => Math.cbrt(2 * x + 8),
    fp: x => 2 / (3 * Math.cbrt(2 * x + 8) ** 2),
    fpTex: "f'(x) = \\dfrac{2}{3(2x + 8)^{2/3}}",
    a: 0, aTex: "0", answerTex: "\\dfrac{1}{6}",
    window: [-3, 3],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt[3]{x + 26}",
    f: x => Math.cbrt(1 * x + 26),
    fp: x => 1 / (3 * Math.cbrt(1 * x + 26) ** 2),
    fpTex: "f'(x) = \\dfrac{1}{3(x + 26)^{2/3}}",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{27}",
    window: [-2, 4],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\dfrac{1}{\\sqrt{x^{2} + 144}}",
    f: x => 1 / Math.sqrt(x ** 2 + 144),
    fp: x => -x / (x ** 2 + 144) ** (3 / 2),
    fpTex: "f'(x) = -\\dfrac{x}{(x^{2} + 144)^{3/2}}",
    a: 5, aTex: "5", answerTex: "-\\dfrac{5}{2197}",
    window: [-104 / 5, 104 / 5],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\dfrac{1}{\\sqrt{x^{2} + 64}}",
    f: x => 1 / Math.sqrt(x ** 2 + 64),
    fp: x => -x / (x ** 2 + 64) ** (3 / 2),
    fpTex: "f'(x) = -\\dfrac{x}{(x^{2} + 64)^{3/2}}",
    a: 6, aTex: "6", answerTex: "-\\dfrac{3}{500}",
    window: [-16, 16],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = (x^{2} + 64)^{3/2}",
    f: x => (x ** 2 + 64) ** (3 / 2),
    fp: x => 3 * x * Math.sqrt(x ** 2 + 64),
    fpTex: "f'(x) = 3x\\sqrt{x^{2} + 64}",
    a: 6, aTex: "6", answerTex: "180",
    window: [-16, 16],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = (x^{2} + 36)^{3/2}",
    f: x => (x ** 2 + 36) ** (3 / 2),
    fp: x => 3 * x * Math.sqrt(x ** 2 + 36),
    fpTex: "f'(x) = 3x\\sqrt{x^{2} + 36}",
    a: -8, aTex: "-8", answerTex: "-240",
    window: [-16, 16],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = (x^{2} + 25)^{3/2}",
    f: x => (x ** 2 + 25) ** (3 / 2),
    fp: x => 3 * x * Math.sqrt(x ** 2 + 25),
    fpTex: "f'(x) = 3x\\sqrt{x^{2} + 25}",
    a: -12, aTex: "-12", answerTex: "-468",
    window: [-104 / 5, 104 / 5],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{x + 24}",
    f: x => Math.sqrt(1 * x + 24),
    fp: x => 1 / (2 * Math.sqrt(1 * x + 24)),
    fpTex: "f'(x) = \\dfrac{1}{2\\sqrt{x + 24}}",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{10}",
    window: [-39 / 2, 56],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{2x + 7}",
    f: x => Math.sqrt(2 * x + 7),
    fp: x => 2 / (2 * Math.sqrt(2 * x + 7)),
    fpTex: "f'(x) = \\dfrac{2}{2\\sqrt{2x + 7}}",
    a: 1, aTex: "1", answerTex: "\\dfrac{1}{3}",
    window: [-2.69, 109 / 10],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{x^{2} + 64}",
    f: x => Math.sqrt(x ** 2 + 64),
    fp: x => x / Math.sqrt(x ** 2 + 64),
    fpTex: "f'(x) = \\dfrac{x}{\\sqrt{x^{2} + 64}}",
    a: -15, aTex: "-15", answerTex: "-\\dfrac{15}{17}",
    window: [-136 / 5, 136 / 5],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{x^{2} + 16}",
    f: x => Math.sqrt(x ** 2 + 16),
    fp: x => x / Math.sqrt(x ** 2 + 16),
    fpTex: "f'(x) = \\dfrac{x}{\\sqrt{x^{2} + 16}}",
    a: -3, aTex: "-3", answerTex: "-\\dfrac{3}{5}",
    window: [-8, 8],
  },
  {
    topic: "Chain rule, radical",
    tex: "f(x) = \\sqrt{x^{2} + 36}",
    f: x => Math.sqrt(x ** 2 + 36),
    fp: x => x / Math.sqrt(x ** 2 + 36),
    fpTex: "f'(x) = \\dfrac{x}{\\sqrt{x^{2} + 36}}",
    a: 8, aTex: "8", answerTex: "\\dfrac{4}{5}",
    window: [-16, 16],
  },

  /* ---- Chain rule, trigonometric ---- */
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\cos(-2x)",
    f: x => Math.cos(-2 * x),
    fp: x => 2 * Math.sin(-2 * x),
    fpTex: "f'(x) = 2\\sin(-2x)",
    a: -5 * Math.PI / 8, aTex: "-\\dfrac{5\\pi}{8}", answerTex: "-\\sqrt{2}",
    window: [-13 * Math.PI / 8, 3 * Math.PI / 8],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\cos(x)",
    f: x => Math.cos(x),
    fp: x => -1 * Math.sin(x),
    fpTex: "f'(x) = -1\\sin(x)",
    a: 7 * Math.PI / 6, aTex: "\\dfrac{7\\pi}{6}", answerTex: "\\dfrac{1}{2}",
    window: [Math.PI / 6, 13 * Math.PI / 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\cos^{4} x",
    f: x => Math.cos(x) ** 4,
    fp: x => -4 * Math.cos(x) ** 3 * Math.sin(x),
    fpTex: "f'(x) = 4\\cos^{3} x\\sin x",
    a: 7 * Math.PI / 6, aTex: "\\dfrac{7\\pi}{6}", answerTex: "-\\dfrac{3\\sqrt{3}}{4}",
    window: [Math.PI / 6, 13 * Math.PI / 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\cos^{4} x",
    f: x => Math.cos(x) ** 4,
    fp: x => -4 * Math.cos(x) ** 3 * Math.sin(x),
    fpTex: "f'(x) = 4\\cos^{3} x\\sin x",
    a: -5 * Math.PI / 6, aTex: "-\\dfrac{5\\pi}{6}", answerTex: "-\\dfrac{3\\sqrt{3}}{4}",
    window: [-11 * Math.PI / 6, Math.PI / 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sec(x)",
    f: x => 1 / Math.cos(x),
    fp: x => 1 * Math.sin(x) / Math.cos(x) ** 2,
    fpTex: "f'(x) = 1\\sec(x)\\tan(x)",
    a: -5 * Math.PI / 6, aTex: "-\\dfrac{5\\pi}{6}", answerTex: "-\\dfrac{2}{3}",
    window: [-7 * Math.PI / 5, -3 * Math.PI / 5],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sec(x)",
    f: x => 1 / Math.cos(x),
    fp: x => 1 * Math.sin(x) / Math.cos(x) ** 2,
    fpTex: "f'(x) = 1\\sec(x)\\tan(x)",
    a: 0, aTex: "0", answerTex: "0",
    window: [-2 * Math.PI / 5, 2 * Math.PI / 5],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(x)",
    f: x => Math.sin(x),
    fp: x => 1 * Math.cos(x),
    fpTex: "f'(x) = 1\\cos(x)",
    a: Math.PI / 3, aTex: "\\dfrac{\\pi}{3}", answerTex: "\\dfrac{1}{2}",
    window: [-2 * Math.PI / 3, 4 * Math.PI / 3],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(-2x)",
    f: x => Math.sin(-2 * x),
    fp: x => -2 * Math.cos(-2 * x),
    fpTex: "f'(x) = -2\\cos(-2x)",
    a: Math.PI / 2, aTex: "\\dfrac{\\pi}{2}", answerTex: "2",
    window: [-Math.PI / 2, 3 * Math.PI / 2],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(2x)",
    f: x => Math.sin(2 * x),
    fp: x => 2 * Math.cos(2 * x),
    fpTex: "f'(x) = 2\\cos(2x)",
    a: 5 * Math.PI / 6, aTex: "\\dfrac{5\\pi}{6}", answerTex: "1",
    window: [-Math.PI / 6, 11 * Math.PI / 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin^{2} x",
    f: x => Math.sin(x) ** 2,
    fp: x => 2 * Math.sin(x) ** 1 * Math.cos(x),
    fpTex: "f'(x) = 2\\sin x\\cos x",
    a: -Math.PI, aTex: "-\\pi", answerTex: "0",
    window: [-2 * Math.PI, 0],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin^{4} x",
    f: x => Math.sin(x) ** 4,
    fp: x => 4 * Math.sin(x) ** 3 * Math.cos(x),
    fpTex: "f'(x) = 4\\sin^{3} x\\cos x",
    a: 11 * Math.PI / 6, aTex: "\\dfrac{11\\pi}{6}", answerTex: "-\\dfrac{\\sqrt{3}}{4}",
    window: [5 * Math.PI / 6, 17 * Math.PI / 6],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(x^{2})",
    f: x => Math.sin(x ** 2),
    fp: x => 2 * x * Math.cos(x ** 2),
    fpTex: "f'(x) = 2x\\cos(x^{2})",
    a: -3 * Math.sqrt(Math.PI), aTex: "-3\\sqrt{\\pi}", answerTex: "6\\sqrt{\\pi}",
    window: [-6.5174, -4.1174],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\sin(x^{2})",
    f: x => Math.sin(x ** 2),
    fp: x => 2 * x * Math.cos(x ** 2),
    fpTex: "f'(x) = 2x\\cos(x^{2})",
    a: 3 * Math.sqrt(Math.PI), aTex: "3\\sqrt{\\pi}", answerTex: "-6\\sqrt{\\pi}",
    window: [4.1174, 6.5174],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\tan(x)",
    f: x => Math.tan(x),
    fp: x => 1 / Math.cos(x) ** 2,
    fpTex: "f'(x) = 1\\sec^{2}(x)",
    a: -3 * Math.PI / 4, aTex: "-\\dfrac{3\\pi}{4}", answerTex: "2",
    window: [-7 * Math.PI / 5, -3 * Math.PI / 5],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\tan(3x)",
    f: x => Math.tan(3 * x),
    fp: x => 3 / Math.cos(3 * x) ** 2,
    fpTex: "f'(x) = 3\\sec^{2}(3x)",
    a: 7 * Math.PI / 12, aTex: "\\dfrac{7\\pi}{12}", answerTex: "6",
    window: [8 * Math.PI / 15, 4 * Math.PI / 5],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\tan^{2} x",
    f: x => Math.tan(x) ** 2,
    fp: x => 2 * Math.tan(x) / Math.cos(x) ** 2,
    fpTex: "f'(x) = 2\\tan x\\sec^{2} x",
    a: -3 * Math.PI / 4, aTex: "-\\dfrac{3\\pi}{4}", answerTex: "4",
    window: [-7 * Math.PI / 5, -3 * Math.PI / 5],
  },
  {
    topic: "Chain rule, trigonometric",
    tex: "f(x) = \\tan^{2} x",
    f: x => Math.tan(x) ** 2,
    fp: x => 2 * Math.tan(x) / Math.cos(x) ** 2,
    fpTex: "f'(x) = 2\\tan x\\sec^{2} x",
    a: -5 * Math.PI / 6, aTex: "-\\dfrac{5\\pi}{6}", answerTex: "\\dfrac{8\\sqrt{3}}{9}",
    window: [-7 * Math.PI / 5, -3 * Math.PI / 5],
  },

  /* ---- Chain rule, exponential ---- */
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{1/x}",
    f: x => Math.exp(1 / x),
    fp: x => -Math.exp(1 / x) / x ** 2,
    fpTex: "f'(x) = -\\dfrac{e^{1/x}}{x^{2}}",
    a: -1, aTex: "-1", answerTex: "-\\dfrac{1}{e}",
    window: [-16 / 5, -9 / 50],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{3x}",
    f: x => Math.exp(3 * x),
    fp: x => 3 * Math.exp(3 * x),
    fpTex: "f'(x) = 3e^{3x}",
    a: -1 / 3, aTex: "-\\dfrac{1}{3}", answerTex: "\\dfrac{3}{e}",
    window: [-7 / 3, 5 / 3],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{3x}",
    f: x => Math.exp(3 * x),
    fp: x => 3 * Math.exp(3 * x),
    fpTex: "f'(x) = 3e^{3x}",
    a: 0, aTex: "0", answerTex: "3",
    window: [-2, 2],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{-x^{3}}",
    f: x => Math.exp(-1 * x ** 3),
    fp: x => -3 * x ** 2 * Math.exp(-1 * x ** 3),
    fpTex: "f'(x) = -3x^{2}e^{-x^{3}}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{3}{e}",
    window: [-1, 3],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{x^{2}}",
    f: x => Math.exp(1 * x ** 2),
    fp: x => 2 * x ** 1 * Math.exp(1 * x ** 2),
    fpTex: "f'(x) = 2xe^{x^{2}}",
    a: -1, aTex: "-1", answerTex: "-2e",
    window: [-5 / 2, 1 / 2],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = e^{\\sqrt{x}}",
    f: x => Math.exp(Math.sqrt(x)),
    fp: x => Math.exp(Math.sqrt(x)) / (2 * Math.sqrt(x)),
    fpTex: "f'(x) = \\dfrac{e^{\\sqrt{x}}}{2\\sqrt{x}}",
    a: 9, aTex: "9", answerTex: "\\dfrac{e^3}{6}",
    window: [27 / 25, 18],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = (e^{x} + 2)^{3}",
    f: x => (Math.exp(x) + 2) ** 3,
    fp: x => 3 * (Math.exp(x) + 2) ** 2 * Math.exp(x),
    fpTex: "f'(x) = 3(e^{x} + 2)^{2}e^{x}",
    a: 0, aTex: "0", answerTex: "27",
    window: [-2, 2],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = (e^{x} + 1)^{2}",
    f: x => (Math.exp(x) + 1) ** 2,
    fp: x => 2 * (Math.exp(x) + 1) ** 1 * Math.exp(x),
    fpTex: "f'(x) = 2(e^{x} + 1)e^{x}",
    a: 0, aTex: "0", answerTex: "4",
    window: [-2, 2],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = xe^{-x}",
    f: x => x * Math.exp(-1 * x),
    fp: x => (1 + -1 * x) * Math.exp(-1 * x),
    fpTex: "f'(x) = (1 - x)e^{-x}",
    a: -1, aTex: "-1", answerTex: "2e",
    window: [-7 / 2, 3 / 2],
  },
  {
    topic: "Chain rule, exponential",
    tex: "f(x) = xe^{-2x}",
    f: x => x * Math.exp(-2 * x),
    fp: x => (1 + -2 * x) * Math.exp(-2 * x),
    fpTex: "f'(x) = (1 - 2x)e^{-2x}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{1}{e^2}",
    window: [-3 / 2, 7 / 2],
  },

  /* ---- Trigonometric ---- */
  {
    topic: "Trigonometric",
    tex: "f(x) = \\sin x + \\cos x",
    f: x => 1 * Math.sin(x) + 1 * Math.cos(x),
    fp: x => 1 * Math.cos(x) - 1 * Math.sin(x),
    fpTex: "f'(x) = \\cos x - \\sin x",
    a: 2 * Math.PI, aTex: "2\\pi", answerTex: "1",
    window: [Math.PI, 3 * Math.PI],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = -\\sin x + \\cos x",
    f: x => -1 * Math.sin(x) + 1 * Math.cos(x),
    fp: x => -1 * Math.cos(x) - 1 * Math.sin(x),
    fpTex: "f'(x) = -\\cos x - \\sin x",
    a: Math.PI, aTex: "\\pi", answerTex: "1",
    window: [0, 2 * Math.PI],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\cos x",
    f: x => 2 * (Math.cos(x)),
    fp: x => 2 * (-Math.sin(x)),
    fpTex: "f'(x) = 2(-\\sin x)",
    a: 0, aTex: "0", answerTex: "0",
    window: [-Math.PI, Math.PI],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\cos x",
    f: x => 2 * (Math.cos(x)),
    fp: x => 2 * (-Math.sin(x)),
    fpTex: "f'(x) = 2(-\\sin x)",
    a: 3 * Math.PI / 4, aTex: "\\dfrac{3\\pi}{4}", answerTex: "-\\sqrt{2}",
    window: [-Math.PI / 4, 7 * Math.PI / 4],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\cos x",
    f: x => 1 * (Math.cos(x)),
    fp: x => 1 * (-Math.sin(x)),
    fpTex: "f'(x) = -\\sin x",
    a: -Math.PI, aTex: "-\\pi", answerTex: "0",
    window: [-2 * Math.PI, 0],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 3\\cot x",
    f: x => 3 * (Math.cos(x) / Math.sin(x)),
    fp: x => 3 * (-1 / Math.sin(x) ** 2),
    fpTex: "f'(x) = 3(-\\csc^{2} x)",
    a: 7 * Math.PI / 6, aTex: "\\dfrac{7\\pi}{6}", answerTex: "-12",
    window: [11 * Math.PI / 10, 19 * Math.PI / 10],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = -\\cot x",
    f: x => -1 * (Math.cos(x) / Math.sin(x)),
    fp: x => -1 * (-1 / Math.sin(x) ** 2),
    fpTex: "f'(x) = \\csc^{2} x",
    a: -Math.PI / 2, aTex: "-\\dfrac{\\pi}{2}", answerTex: "1",
    window: [-9 * Math.PI / 10, -Math.PI / 10],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\cot x",
    f: x => 2 * (Math.cos(x) / Math.sin(x)),
    fp: x => 2 * (-1 / Math.sin(x) ** 2),
    fpTex: "f'(x) = 2(-\\csc^{2} x)",
    a: -Math.PI / 3, aTex: "-\\dfrac{\\pi}{3}", answerTex: "-\\dfrac{8}{3}",
    window: [-9 * Math.PI / 10, -Math.PI / 10],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\csc x",
    f: x => 2 * (1 / Math.sin(x)),
    fp: x => 2 * (-Math.cos(x) / Math.sin(x) ** 2),
    fpTex: "f'(x) = 2(-\\csc x\\cot x)",
    a: Math.PI / 2, aTex: "\\dfrac{\\pi}{2}", answerTex: "0",
    window: [Math.PI / 10, 9 * Math.PI / 10],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\csc x",
    f: x => 1 * (1 / Math.sin(x)),
    fp: x => 1 * (-Math.cos(x) / Math.sin(x) ** 2),
    fpTex: "f'(x) = -\\csc x\\cot x",
    a: 4 * Math.PI / 3, aTex: "\\dfrac{4\\pi}{3}", answerTex: "\\dfrac{2}{3}",
    window: [11 * Math.PI / 10, 19 * Math.PI / 10],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\csc x",
    f: x => 1 * (1 / Math.sin(x)),
    fp: x => 1 * (-Math.cos(x) / Math.sin(x) ** 2),
    fpTex: "f'(x) = -\\csc x\\cot x",
    a: 5 * Math.PI / 6, aTex: "\\dfrac{5\\pi}{6}", answerTex: "2\\sqrt{3}",
    window: [0.2199, 2.9217],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\sec x",
    f: x => 1 * (1 / Math.cos(x)),
    fp: x => 1 * (Math.sin(x) / Math.cos(x) ** 2),
    fpTex: "f'(x) = \\sec x\\tan x",
    a: 11 * Math.PI / 6, aTex: "\\dfrac{11\\pi}{6}", answerTex: "-\\dfrac{2}{3}",
    window: [8 * Math.PI / 5, 12 * Math.PI / 5],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\sec x",
    f: x => 1 * (1 / Math.cos(x)),
    fp: x => 1 * (Math.sin(x) / Math.cos(x) ** 2),
    fpTex: "f'(x) = \\sec x\\tan x",
    a: 4 * Math.PI / 3, aTex: "\\dfrac{4\\pi}{3}", answerTex: "-2\\sqrt{3}",
    window: [1.7907, 4.4925],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 3\\sec x",
    f: x => 3 * (1 / Math.cos(x)),
    fp: x => 3 * (Math.sin(x) / Math.cos(x) ** 2),
    fpTex: "f'(x) = 3\\sec x\\tan x",
    a: Math.PI / 4, aTex: "\\dfrac{\\pi}{4}", answerTex: "3\\sqrt{2}",
    window: [-2 * Math.PI / 5, 2 * Math.PI / 5],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 3\\sin x",
    f: x => 3 * (Math.sin(x)),
    fp: x => 3 * (Math.cos(x)),
    fpTex: "f'(x) = 3\\cos x",
    a: -5 * Math.PI / 6, aTex: "-\\dfrac{5\\pi}{6}", answerTex: "-\\dfrac{3\\sqrt{3}}{2}",
    window: [-11 * Math.PI / 6, Math.PI / 6],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\sin x",
    f: x => 2 * (Math.sin(x)),
    fp: x => 2 * (Math.cos(x)),
    fpTex: "f'(x) = 2\\cos x",
    a: 7 * Math.PI / 6, aTex: "\\dfrac{7\\pi}{6}", answerTex: "-\\sqrt{3}",
    window: [Math.PI / 6, 13 * Math.PI / 6],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = -\\sin x",
    f: x => -1 * (Math.sin(x)),
    fp: x => -1 * (Math.cos(x)),
    fpTex: "f'(x) = -\\cos x",
    a: 2 * Math.PI, aTex: "2\\pi", answerTex: "-1",
    window: [Math.PI, 3 * Math.PI],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 3\\tan x",
    f: x => 3 * (Math.tan(x)),
    fp: x => 3 * (1 / Math.cos(x) ** 2),
    fpTex: "f'(x) = 3\\sec^{2} x",
    a: 2 * Math.PI / 3, aTex: "\\dfrac{2\\pi}{3}", answerTex: "12",
    window: [3 * Math.PI / 5, 7 * Math.PI / 5],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = 2\\tan x",
    f: x => 2 * (Math.tan(x)),
    fp: x => 2 * (1 / Math.cos(x) ** 2),
    fpTex: "f'(x) = 2\\sec^{2} x",
    a: 5 * Math.PI / 3, aTex: "\\dfrac{5\\pi}{3}", answerTex: "8",
    window: [8 * Math.PI / 5, 12 * Math.PI / 5],
  },
  {
    topic: "Trigonometric",
    tex: "f(x) = \\tan x",
    f: x => 1 * (Math.tan(x)),
    fp: x => 1 * (1 / Math.cos(x) ** 2),
    fpTex: "f'(x) = \\sec^{2} x",
    a: -Math.PI / 4, aTex: "-\\dfrac{\\pi}{4}", answerTex: "2",
    window: [-2 * Math.PI / 5, 2 * Math.PI / 5],
  },

  /* ---- Exponential ---- */
  {
    topic: "Exponential",
    tex: "f(x) = 2e^{x} + 1",
    f: x => 2 * Math.exp(x) + 0 * x + 1,
    fp: x => 2 * Math.exp(x) + 0,
    fpTex: "f'(x) = 2e^{x}",
    a: -2, aTex: "-2", answerTex: "\\dfrac{2}{e^2}",
    window: [-5, -1 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = 2e^{x} + 2x",
    f: x => 2 * Math.exp(x) + 2 * x + -1,
    fp: x => 2 * Math.exp(x) + 2,
    fpTex: "f'(x) = 2e^{x} + 2",
    a: 1, aTex: "1", answerTex: "2e + 2",
    window: [-2, 5 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = e^{x} - x",
    f: x => 1 * Math.exp(x) + -1 * x + 0,
    fp: x => 1 * Math.exp(x) + -1,
    fpTex: "f'(x) = e^{x} - 1",
    a: 0, aTex: "0", answerTex: "1 - 1",
    window: [-3, 3 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = 3e^{x} - x",
    f: x => 3 * Math.exp(x) + -1 * x + 0,
    fp: x => 3 * Math.exp(x) + -1,
    fpTex: "f'(x) = 3e^{x} - 1",
    a: -2, aTex: "-2", answerTex: "\\dfrac{3}{e^2} - 1",
    window: [-5, -1 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = -e^{x} + x",
    f: x => -1 * Math.exp(x) + 1 * x + 0,
    fp: x => -1 * Math.exp(x) + 1,
    fpTex: "f'(x) = -e^{x} + 1",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{1}{e^2} + 1",
    window: [-5, -1 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = 3e^{x} + 1",
    f: x => 3 * Math.exp(x) + 0 * x + 1,
    fp: x => 3 * Math.exp(x) + 0,
    fpTex: "f'(x) = 3e^{x}",
    a: 1, aTex: "1", answerTex: "3e",
    window: [-2, 5 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = -2e^{x} - x",
    f: x => -2 * Math.exp(x) + -1 * x + 0,
    fp: x => -2 * Math.exp(x) + -1,
    fpTex: "f'(x) = -2e^{x} - 1",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{2}{e^2} - 1",
    window: [-5, -1 / 2],
  },
  {
    topic: "Exponential",
    tex: "f(x) = -e^{x} - x",
    f: x => -1 * Math.exp(x) + -1 * x + 0,
    fp: x => -1 * Math.exp(x) + -1,
    fpTex: "f'(x) = -e^{x} - 1",
    a: 0, aTex: "0", answerTex: "-1 - 1",
    window: [-3, 3 / 2],
  },

  /* ---- Exponential, general base ---- */
  {
    topic: "Exponential, general base",
    tex: "f(x) = 3^{3x}",
    f: x => 3 ** (3 * x),
    fp: x => 3 * 3 ** (3 * x) * Math.log(3),
    fpTex: "f'(x) = 33^{3x}\\ln 3",
    a: 0, aTex: "0", answerTex: "3\\ln(3)",
    window: [-2, 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = 3^{3x}",
    f: x => 3 ** (3 * x),
    fp: x => 3 * 3 ** (3 * x) * Math.log(3),
    fpTex: "f'(x) = 33^{3x}\\ln 3",
    a: 2 / 3, aTex: "\\dfrac{2}{3}", answerTex: "27\\ln(3)",
    window: [-8 / 15, 28 / 15],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = 3^{x^{2}}",
    f: x => 3 ** (x ** 2),
    fp: x => 2 * x * 3 ** (x ** 2) * Math.log(3),
    fpTex: "f'(x) = 2x\\,3^{x^{2}}\\ln 3",
    a: 0, aTex: "0", answerTex: "0",
    window: [-8 / 5, 8 / 5],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = 2^{x^{2}}",
    f: x => 2 ** (x ** 2),
    fp: x => 2 * x * 2 ** (x ** 2) * Math.log(2),
    fpTex: "f'(x) = 2x\\,2^{x^{2}}\\ln 2",
    a: -1, aTex: "-1", answerTex: "-4\\ln(2)",
    window: [-13 / 5, 3 / 5],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = -3^{x}",
    f: x => -1 * 3 ** x,
    fp: x => -1 * 3 ** x * Math.log(3),
    fpTex: "f'(x) = -3^{x}\\ln 3",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{\\ln(3)}{9}",
    window: [-5, -1 / 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = 3^{x}",
    f: x => 1 * 3 ** x,
    fp: x => 1 * 3 ** x * Math.log(3),
    fpTex: "f'(x) = 3^{x}\\ln 3",
    a: 0, aTex: "0", answerTex: "\\ln(3)",
    window: [-3, 3 / 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = \\left(\\dfrac{1}{2}\\right)^{x}",
    f: x => (1 / 2) ** x,
    fp: x => -((1 / 2) ** x) * Math.log(2),
    fpTex: "f'(x) = -\\dfrac{\\ln 2}{2^{x}}",
    a: 2, aTex: "2", answerTex: "-\\dfrac{\\ln(2)}{4}",
    window: [-1 / 2, 9 / 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = \\left(\\dfrac{1}{2}\\right)^{x}",
    f: x => (1 / 2) ** x,
    fp: x => -((1 / 2) ** x) * Math.log(2),
    fpTex: "f'(x) = -\\dfrac{\\ln 2}{2^{x}}",
    a: 1, aTex: "1", answerTex: "-\\dfrac{\\ln(2)}{2}",
    window: [-3 / 2, 7 / 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = x\\,3^{x}",
    f: x => x * 3 ** x,
    fp: x => 3 ** x * (1 + x * Math.log(3)),
    fpTex: "f'(x) = 3^{x}(1 + x\\ln 3)",
    a: 1, aTex: "1", answerTex: "3 + 3\\ln(3)",
    window: [-2, 5 / 2],
  },
  {
    topic: "Exponential, general base",
    tex: "f(x) = x\\,2^{x}",
    f: x => x * 2 ** x,
    fp: x => 2 ** x * (1 + x * Math.log(2)),
    fpTex: "f'(x) = 2^{x}(1 + x\\ln 2)",
    a: 0, aTex: "0", answerTex: "1",
    window: [-3, 3 / 2],
  },

  /* ---- Logarithm ---- */
  {
    topic: "Logarithm",
    tex: "f(x) = 3\\ln(2x)",
    f: x => 3 * Math.log(2 * x),
    fp: x => 3 / x,
    fpTex: "f'(x) = \\dfrac{3}{x}",
    a: 6, aTex: "6", answerTex: "\\dfrac{1}{2}",
    window: [3 / 5, 72 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln(2x)",
    f: x => 1 * Math.log(2 * x),
    fp: x => 1 / x,
    fpTex: "f'(x) = \\dfrac{1}{x}",
    a: 1, aTex: "1", answerTex: "1",
    window: [1 / 10, 12 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = -\\ln(3x)",
    f: x => -1 * Math.log(3 * x),
    fp: x => -1 / x,
    fpTex: "f'(x) = -\\dfrac{1}{x}",
    a: 4, aTex: "4", answerTex: "-\\dfrac{1}{4}",
    window: [2 / 5, 48 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln x - x",
    f: x => Math.log(x) + -1 * x,
    fp: x => 1 / x + -1,
    fpTex: "f'(x) = \\dfrac{1}{x} - 1",
    a: 2, aTex: "2", answerTex: "-\\dfrac{1}{2}",
    window: [1 / 5, 24 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln x + x",
    f: x => Math.log(x) + 1 * x,
    fp: x => 1 / x + 1,
    fpTex: "f'(x) = \\dfrac{1}{x} + 1",
    a: 1, aTex: "1", answerTex: "2",
    window: [1 / 10, 12 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln x + 2x",
    f: x => Math.log(x) + 2 * x,
    fp: x => 1 / x + 2,
    fpTex: "f'(x) = \\dfrac{1}{x} + 2",
    a: 1, aTex: "1", answerTex: "3",
    window: [1 / 10, 12 / 5],
  },
  {
    topic: "Logarithm",
    tex: "f(x) = \\ln x + x",
    f: x => Math.log(x) + 1 * x,
    fp: x => 1 / x + 1,
    fpTex: "f'(x) = \\dfrac{1}{x} + 1",
    a: 2, aTex: "2", answerTex: "\\dfrac{3}{2}",
    window: [1 / 5, 24 / 5],
  },

  /* ---- Logarithm, chain rule ---- */
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\ln(\\cos x)",
    f: x => Math.log(Math.cos(x)),
    fp: x => -Math.tan(x),
    fpTex: "f'(x) = -\\tan x",
    a: 2 * Math.PI, aTex: "2\\pi", answerTex: "0",
    window: [8 * Math.PI / 5, 12 * Math.PI / 5],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\ln(3x + 1)",
    f: x => Math.log(3 * x + 1),
    fp: x => 3 / (3 * x + 1),
    fpTex: "f'(x) = \\dfrac{3}{3x + 1}",
    a: 2, aTex: "2", answerTex: "\\dfrac{3}{7}",
    window: [0.0867, 107 / 15],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = (\\ln x)^{2}",
    f: x => Math.log(x) ** 2,
    fp: x => 2 * Math.log(x) ** 1 / x,
    fpTex: "f'(x) = \\dfrac{2(\\ln x)}{x}",
    a: Math.E ** 2, aTex: "e^{2}", answerTex: "\\dfrac{4}{e^2}",
    window: [1 / 20, 16.2559],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = (\\ln x)^{3}",
    f: x => Math.log(x) ** 3,
    fp: x => 3 * Math.log(x) ** 2 / x,
    fpTex: "f'(x) = \\dfrac{3(\\ln x)^{2}}{x}",
    a: Math.E, aTex: "e", answerTex: "\\dfrac{3}{e}",
    window: [1 / 20, 11 * Math.E / 5],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\ln(x^{2} + 1)",
    f: x => Math.log(x ** 2 + 1),
    fp: x => 2 * x / (x ** 2 + 1),
    fpTex: "f'(x) = \\dfrac{2x}{x^{2} + 1}",
    a: -3, aTex: "-3", answerTex: "-\\dfrac{3}{5}",
    window: [-7, 1],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\ln(\\sin x)",
    f: x => Math.log(Math.sin(x)),
    fp: x => Math.cos(x) / Math.sin(x),
    fpTex: "f'(x) = \\cot x",
    a: Math.PI / 6, aTex: "\\dfrac{\\pi}{6}", answerTex: "\\sqrt{3}",
    window: [Math.PI / 10, 9 * Math.PI / 10],
  },
  {
    topic: "Logarithm, chain rule",
    tex: "f(x) = \\sqrt{\\ln x}",
    f: x => Math.sqrt(Math.log(x)),
    fp: x => 1 / (2 * x * Math.sqrt(Math.log(x))),
    fpTex: "f'(x) = \\dfrac{1}{2x\\sqrt{\\ln x}}",
    a: Math.E ** 4, aTex: "e^{4}", answerTex: "\\dfrac{1}{4e^4}",
    window: [51 / 50, 87.357],
  },

  /* ---- Logarithm, general base ---- */
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{2}(x - 1)",
    f: x => Math.log(1 * x - 1) / Math.log(2),
    fp: x => 1 / ((1 * x - 1) * Math.log(2)),
    fpTex: "f'(x) = \\dfrac{1}{(x - 1)\\ln 2}",
    a: 3, aTex: "3", answerTex: "\\dfrac{1}{2\\ln(2)}",
    window: [34 / 25, 37 / 5],
  },
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{3}(x - 1)",
    f: x => Math.log(1 * x - 1) / Math.log(3),
    fp: x => 1 / ((1 * x - 1) * Math.log(3)),
    fpTex: "f'(x) = \\dfrac{1}{(x - 1)\\ln 3}",
    a: 3, aTex: "3", answerTex: "\\dfrac{1}{2\\ln(3)}",
    window: [34 / 25, 37 / 5],
  },
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{2}(x^{2} + 9)",
    f: x => Math.log(x ** 2 + 9) / Math.log(2),
    fp: x => 2 * x / ((x ** 2 + 9) * Math.log(2)),
    fpTex: "f'(x) = \\dfrac{2x}{(x^{2} + 9)\\ln 2}",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{4}{13\\ln(2)}",
    window: [-6, 2],
  },
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{3}(x^{2} + 9)",
    f: x => Math.log(x ** 2 + 9) / Math.log(3),
    fp: x => 2 * x / ((x ** 2 + 9) * Math.log(3)),
    fpTex: "f'(x) = \\dfrac{2x}{(x^{2} + 9)\\ln 3}",
    a: -2, aTex: "-2", answerTex: "-\\dfrac{4}{13\\ln(3)}",
    window: [-6, 2],
  },
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{3} x",
    f: x => Math.log(x) / Math.log(3),
    fp: x => 1 / (x * Math.log(3)),
    fpTex: "f'(x) = \\dfrac{1}{x\\ln 3}",
    a: 8, aTex: "8", answerTex: "\\dfrac{1}{8\\ln(3)}",
    window: [4 / 5, 96 / 5],
  },
  {
    topic: "Logarithm, general base",
    tex: "f(x) = \\log_{2} x",
    f: x => Math.log(x) / Math.log(2),
    fp: x => 1 / (x * Math.log(2)),
    fpTex: "f'(x) = \\dfrac{1}{x\\ln 2}",
    a: 2, aTex: "2", answerTex: "\\dfrac{1}{2\\ln(2)}",
    window: [1 / 5, 24 / 5],
  },
];

if (typeof module !== "undefined") module.exports = { PROBLEMS };
