"""Ray class field lattice over the Hilbert class field, with cyclotomic intersections.

For an imaginary quadratic field K of fundamental discriminant D_K and a rational
integer modulus m, this computes the lattice of fields

    H_K subset L subset K_(m)

together with L cap Q(zeta_m) for every L.  The intersection is computed from the
single homomorphism

    nu : Cl_(m) -> (Z/m)^x,   [a] |-> N(a) mod m,

which is the restriction map Gal(K_(m)/K) -> Gal(Q(zeta_m)/Q) under Artin
reciprocity.  If L is the fixed field of U <= Cl_(m), then

    L cap Q(zeta_m) = Q(zeta_m) ^ nu(U).
"""

from __future__ import annotations

import json
import math
import re
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

from sage.all import (
    PolynomialRing,
    QuadraticField,
    ZZ,
    hilbert_class_polynomial,
    pari,
)
from sage.schemes.elliptic_curves.constructor import EllipticCurve_from_j

ROOT = Path(__file__).resolve().parent

MAX_M = 7
MAX_ABS_D = 500
MAX_RAY_ORDER = 20000
MAX_NODES = 300
MAX_CYCLO_NODES = 200
MAX_POLRED_DEGREE = 20


# ---------------------------------------------------------------- arithmetic


def is_squarefree(n):
    n = abs(n)
    p = 2
    while p * p <= n:
        if n % (p * p) == 0:
            return False
        p += 1
    return True


def is_fundamental_discriminant(D):
    if D >= 0:
        return False
    if D % 4 == 1:
        return is_squarefree(D)
    if D % 4:
        return False
    d = D // 4
    return is_squarefree(d) and d % 4 in (2, 3)


def is_prime(n):
    if n < 2:
        return False
    p = 2
    while p * p <= n:
        if n % p == 0:
            return False
        p += 1
    return True


def divisors(n):
    return [d for d in range(1, n + 1) if n % d == 0]


def squarefree_part(n):
    sign = -1 if n < 0 else 1
    n = abs(n)
    out = 1
    p = 2
    while p * p <= n:
        e = 0
        while n % p == 0:
            n //= p
            e += 1
        if e % 2:
            out *= p
        p += 1
    return sign * out * n


def latex_polynomial(text):
    """PARI's polynomial printing into LaTeX: x^12 -> x^{12}, 3/2*x -> \\frac{3}{2} x."""
    out = re.sub(r"\^(\d+)", r"^{\1}", text)
    out = re.sub(r"(\d+)/(\d+)", r"\\frac{\1}{\2}", out)
    return out.replace("*", " ")


# ------------------------------------------------------- abstract subgroups


def abelian_closure(gens, cyc):
    """Subgroup of prod Z/cyc_i generated by `gens`, as a frozenset of tuples."""
    zero = tuple([0] * len(cyc))
    S = {zero}
    for g in gens:
        if g in S:
            continue
        base = list(S)
        shift = g
        while shift not in S:
            S.update(
                tuple((a + b) % c for a, b, c in zip(x, shift, cyc)) for x in base
            )
            shift = tuple((a + b) % c for a, b, c in zip(shift, g, cyc))
    return frozenset(S)


def unit_join(S, u, m):
    """<S, u> inside (Z/m)^x, for S a subgroup containing 1."""
    t, p = 1, u % m
    while p not in S:
        p = (p * u) % m
        t += 1
    T, p = set(), 1
    for _ in range(t):
        T.update((x * p) % m for x in S)
        p = (p * u) % m
    return frozenset(T)


def covering_edges(subgroups):
    """Covering pairs (i, j) with subgroups[i] < subgroups[j] of prime index.

    In an abelian group a strict inclusion has no intermediate subgroup exactly
    when its index is prime, so no further minimality test is needed.  The
    Galois correspondence reverses inclusion, so a pair (i, j) here means that
    the field of j sits below the field of i; both callers emit the edge as
    [lower field, upper field].
    """
    edges = []
    for i, small in enumerate(subgroups):
        for j, large in enumerate(subgroups):
            if len(large) <= len(small) or len(large) % len(small):
                continue
            if not is_prime(len(large) // len(small)):
                continue
            if small <= large:
                edges.append((i, j))
    return edges


# ------------------------------------------------ subfields of Q(zeta_m)


def cyclotomic_subfields(m):
    """Every subfield of Q(zeta_m), indexed by the subgroup of (Z/m)^x fixing it."""
    units = [x for x in range(1, max(m, 2)) if math.gcd(x, m) == 1] if m > 2 else [1]
    phi = len(units)

    trivial = frozenset({1})
    subgroups = {trivial}
    queue = [trivial]
    while queue:
        S = queue.pop()
        for u in units:
            if u in S:
                continue
            T = unit_join(S, u, m)
            if T not in subgroups:
                subgroups.add(T)
                queue.append(T)
                if len(subgroups) > MAX_CYCLO_NODES:
                    raise ValueError(
                        "Q(zeta_%s) has more than %s subfields; try a smaller m."
                        % (m, MAX_CYCLO_NODES)
                    )

    ordered = sorted(subgroups, key=lambda S: (len(S), sorted(S)))
    nodes = [describe_subfield(m, S, phi) for S in ordered]
    edges = [[j, i] for i, j in covering_edges(ordered)]
    return ordered, {"m": m, "phi": phi, "nodes": nodes, "edges": edges}


def conductor_of_subfield(m, S):
    """Least f | m with the fixed field of S inside Q(zeta_f)."""
    for f in divisors(m):
        kernel = [u for u in range(1, max(m, 2))
                  if math.gcd(u, m) == 1 and u % f == 1 % f]
        if all(u in S for u in kernel):
            return f
    return m


def roots_of_unity(m, S):
    """Largest n with mu_n inside the fixed field of S."""
    best = 1
    for n in divisors(m):
        if all(u % n == 1 % n for u in S):
            best = max(best, n)
    return best if best % 2 == 0 else 2 * best


def subfield_polynomial(m, S, degree):
    if degree == 1:
        return "x"
    if len(S) == 1:
        pol = pari.polcyclo(ZZ(m))
    else:
        pol = pari.galoissubcyclo(pari.znstar(ZZ(m), 1), pari(sorted(S - {1})))
    if degree <= MAX_POLRED_DEGREE:
        pol = pari.polredabs(pol)
    return str(pol)


def describe_subfield(m, S, phi):
    degree = phi // len(S)
    f = conductor_of_subfield(m, S)
    polynomial = subfield_polynomial(m, S, degree)
    phi_f = len([x for x in range(1, max(f, 2)) if math.gcd(x, f) == 1]) if f > 2 else 1

    if degree == 1:
        name = short = "Q"
        latex = latex_short = r"\mathbb{Q}"
    elif degree == phi_f:
        name = short = "Q(z_%s)" % f
        latex = latex_short = r"\mathbb{Q}(\zeta_{%s})" % f
    elif degree * 2 == phi_f and (m - 1) % m in S:
        name = short = "Q(z_%s)+" % f
        latex = latex_short = r"\mathbb{Q}(\zeta_{%s})^{+}" % f
    elif degree == 2:
        # x^2 + bx + c  ->  Q(sqrt(b^2 - 4c))
        pol = pari(polynomial)
        b, c = int(pol.polcoef(1)), int(pol.polcoef(0))
        d = squarefree_part(b * b - 4 * c)
        name = short = "Q(sqrt %s)" % d
        latex = latex_short = r"\mathbb{Q}(\sqrt{%s})" % d
    else:
        # No standard name; the node caption stays terse and the detail panel
        # carries the conductor and the defining polynomial.
        name = "deg %s in Q(z_%s)" % (degree, f)
        short = "deg %s" % degree
        latex = r"\text{degree } %s \text{ subfield of } \mathbb{Q}(\zeta_{%s})" % (degree, f)
        latex_short = r"\text{deg } %s" % degree

    return {
        "degree": degree,
        "name": name,
        "short": short,
        "latex": latex,
        "latex_short": latex_short,
        "conductor": f,
        "polynomial": polynomial,
        "polynomial_latex": latex_polynomial(polynomial),
        "roots_of_unity": roots_of_unity(m, S),
        "subgroup": sorted(S),
    }


# ----------------------------------------------------------- the main lattice


def cm_construction(K, D, m):
    hilbert_polynomial = hilbert_class_polynomial(D)
    polynomial_ring = PolynomialRing(K, "T")
    polynomial_over_K = polynomial_ring(hilbert_polynomial)
    H = K.extension(polynomial_over_K, "j")
    j = H.gen()
    curve = EllipticCurve_from_j(j)
    division_polynomial = curve.division_polynomial(m)

    if m == 1:
        return {
            "hilbert_class_polynomial": str(hilbert_polynomial),
            "hilbert_absolute_degree": int(H.absolute_degree()),
            "chosen_j": str(j),
            "curve_a_invariants": [str(a) for a in curve.a_invariants()],
            "division_polynomial": "1",
            "division_polynomial_degree": 0,
            "weber_function": "none (trivial modulus)",
            "weber_polynomial": "1",
            "weber_factor_degrees_over_H": [],
            "ray_field_defining_polynomial": str(H.absolute_polynomial()),
            "ray_field_absolute_degree": int(H.absolute_degree()),
        }

    if D == -4:
        weber_exponent = 2
    elif D == -3:
        weber_exponent = 3
    else:
        weber_exponent = 1

    if weber_exponent == 1:
        weber_polynomial = division_polynomial
    else:
        y_ring = PolynomialRing(H, "y")
        y = y_ring.gen()
        xy_ring = PolynomialRing(y_ring, "x")
        x = xy_ring.gen()
        resultant = xy_ring(division_polynomial).resultant(
            x ** weber_exponent - xy_ring(y)
        )
        weber_polynomial = y_ring(resultant).radical().monic()

    factor_degrees = []
    for factor, multiplicity in weber_polynomial.factor():
        factor_degrees += [int(factor.degree())] * int(multiplicity)

    R = weber_polynomial.splitting_field("u")
    return {
        "hilbert_class_polynomial": str(hilbert_polynomial),
        "hilbert_absolute_degree": int(H.absolute_degree()),
        "chosen_j": str(j),
        "curve_a_invariants": [str(a) for a in curve.a_invariants()],
        "division_polynomial": str(division_polynomial),
        "division_polynomial_degree": int(division_polynomial.degree()),
        "weber_function": (
            "x" if weber_exponent == 1 else "x^%s" % weber_exponent
        ),
        "weber_polynomial": str(weber_polynomial),
        "weber_factor_degrees_over_H": factor_degrees,
        "ray_field_defining_polynomial": str(R.polynomial()),
        "ray_field_absolute_degree": int(R.absolute_degree()),
    }


def compute(payload):
    D = payload.get("discriminant")
    m = payload.get("modulus")
    if type(D) is not int or type(m) is not int:
        raise ValueError("The discriminant and modulus must be integers.")
    if not is_fundamental_discriminant(D):
        raise ValueError("%s is not a negative fundamental discriminant." % D)
    if m < 1:
        raise ValueError("The modulus m must be a positive integer.")
    if m % 2 == 0:
        raise ValueError("This construction requires an odd modulus m.")
    if m > MAX_M:
        raise ValueError("Explicit construction currently requires m <= %s." % MAX_M)
    if abs(D) > MAX_ABS_D:
        raise ValueError("Explicit construction currently requires |D_K| <= %s." % MAX_ABS_D)

    K = QuadraticField(ZZ(D), "a")
    bnf = K.pari_bnf()
    bnr = bnf.bnrinit(ZZ(m), 1)

    cyc = [int(x) for x in bnr[4][1]]
    gens = bnr[4][2]
    ray_order = 1
    for c in cyc:
        ray_order *= c
    if ray_order > MAX_RAY_ORDER:
        raise ValueError(
            "The ray class group has order %s; the prototype limit is %s."
            % (ray_order, MAX_RAY_ORDER)
        )

    class_cyc = [int(x) for x in bnf.getattr("cyc")]
    class_number = int(bnf.getattr("no"))
    relative_order = ray_order // class_number

    # Images of the ray class generators in Cl_K and in (Z/m)^x.
    class_images = [[int(v) for v in bnf.bnfisprincipal(g, 0)] for g in gens]
    norms = [1] * len(gens) if m <= 2 else [int(bnf.idealnorm(g)) % m for g in gens]

    subgroup_sets, cyclotomic = cyclotomic_subfields(m)
    cyclo_index = {S: i for i, S in enumerate(subgroup_sets)}

    def in_kernel(column):
        for j, c in enumerate(class_cyc):
            if sum(v * img[j] for v, img in zip(column, class_images)) % c:
                return False
        return True

    def nu(column):
        r = 1
        for v, n in zip(column, norms):
            r = (r * pow(n, v, max(m, 1))) % max(m, 1)
        return r if m > 2 else 1

    # Enumerate subgroups of Cl_(m) with PARI, keep those inside the kernel of
    # Cl_(m) -> Cl_K, which are exactly the fields between H_K and K_(m).
    if not cyc:
        raw = [[]]
    else:
        raw = []
        for M in bnr.subgrouplist(ray_order, 1):
            raw.append([[int(M[j][i]) % cyc[i] for i in range(len(cyc))]
                        for j in range(len(cyc))])

    entries = []
    for columns in raw:
        if not all(in_kernel(col) for col in columns):
            continue
        elements = abelian_closure([tuple(col) for col in columns], cyc)
        image = frozenset({1})
        for col in columns:
            image = unit_join(image, nu(col), max(m, 2)) if m > 2 else image
        entries.append((elements, image))
        if len(entries) > MAX_NODES:
            raise ValueError(
                "The lattice has more than %s fields; try a smaller modulus."
                % MAX_NODES
            )

    entries.sort(key=lambda e: (len(e[0]), sorted(e[0])))
    subgroups = [e[0] for e in entries]

    # The least field in the lattice containing all of Q(zeta_m).
    marked = max(
        (i for i, (_, image) in enumerate(entries) if image == frozenset({1})),
        key=lambda i: len(subgroups[i]),
    )

    nodes = []
    for i, (elements, image) in enumerate(entries):
        nodes.append({
            "id": i,
            "degree_over_hilbert": relative_order // len(elements),
            "degree_under_ray": len(elements),
            "cyclotomic": cyclo_index[image],
            "is_hilbert": len(elements) == relative_order,
            "is_ray": len(elements) == 1,
            "is_cyclotomic_join": i == marked,
        })
    edges = [[j, i] for i, j in covering_edges(subgroups)]

    construction = cm_construction(K, D, m)
    expected_absolute_degree = 2 * ray_order
    construction["expected_absolute_degree"] = expected_absolute_degree
    construction["degree_matches_class_field_theory"] = (
        construction["ray_field_absolute_degree"] == expected_absolute_degree
    )

    return {
        "input": {"discriminant": D, "modulus": m},
        "field": {
            # D_K is the discriminant; the field is named by its squarefree part.
            "label": "Q(sqrt %s)" % squarefree_part(D),
            "latex": r"\mathbb{Q}(\sqrt{%s})" % squarefree_part(D),
            "class_number": class_number,
            "class_group_invariants": class_cyc,
        },
        "ray_class_group": {"invariants": cyc, "order": ray_order},
        "degrees": {
            "ray_over_K": ray_order,
            "hilbert_over_K": class_number,
            "ray_over_hilbert": relative_order,
        },
        "cyclotomic": cyclotomic,
        "lattice": {"nodes": nodes, "edges": edges},
        "construction": construction,
    }


# -------------------------------------------------------------------- server


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def do_POST(self):
        if urlparse(self.path).path != "/api/compute":
            self.send_error(404)
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if length > 4096:
                raise ValueError("Request is too large.")
            payload = json.loads(self.rfile.read(length))
            body = json.dumps({"ok": True, "result": compute(payload)}).encode()
            status = 200
        except (ValueError, TypeError, json.JSONDecodeError) as error:
            body = json.dumps({"ok": False, "error": str(error)}).encode()
            status = 400
        except Exception as error:
            print("Computation error:", repr(error))
            body = json.dumps(
                {"ok": False, "error": "The computation failed unexpectedly."}
            ).encode()
            status = 500
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


if __name__ == "__main__":
    print("Ray class lattice app: http://localhost:8000")
    HTTPServer(("0.0.0.0", 8000), Handler).serve_forever()
